### ISSUE TITLE
RegisterCommands不起作用

### ISSUE THREAD

**Issue by qaz197418i** [InsinuateProjects/TrMenu#10]
服务器版本：paper 1.12.2
TrMenu版本：最新3.0-pre13
RegisterCommands配置后不起作用，命令有被注册可以被tab补全，但是输入后没有任何效果，后台无报错
![image](https://user-images.githubusercontent.com/30312760/128625527-e9b3d3b3-e830-4d7a-9065-38081d6282ba.png)
![image](https://user-images.githubusercontent.com/30312760/128625507-6ab57809-1f82-48fd-b898-d168d0c44696.png)

**Comment by Score2** [comment]
Fixed
