### ISSUE TITLE
[Bug]: TrMenu与登陆插件问题

### ISSUE THREAD

**Issue by MCJiaoLong** [InsinuateProjects/TrMenu#114]
### 📚 Have you checked the Wiki

- [x] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

[Server thread/INFO]: 未知的命令.使用/help 查看命令帮助.

### 🔍 Detailed description

根据先前的问题,我发现,
TrMenu与登陆插件存在bug
当安装登陆插件(CatSeedLogin,Authme)时,
就会出现打开菜单点东西掉线的情况
且需要开bc
服务端插件:
![QQ图片20220114213910](https://user-images.githubusercontent.com/75253383/149524397-17ecf92f-2c06-4510-ab4f-95dda466caa8.png)

### 🗄 Server log
子服务器显示:
![QQ图片20211218085525](https://user-images.githubusercontent.com/75253383/146623439-575df45b-399f-48f0-8ea6-a9cbe4101ac2.png)
bc显示:
![QQ图片20211218090023](https://user-images.githubusercontent.com/75253383/146623623-a4bd00d8-537a-49b4-b2f0-cc9bb00adc46.png)
bc文本:
xx:xx:xx [信息] [xxxxxxxx] disconnected with: §fDecoderException : java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledSlicedByteBuf(ridx: 1, widx: 1, cap: 1/1, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 1024)) @ io.netty.handler.codec.MessageToMessageDecoder:98
客户端显示
![QQ图片20211218085838](https://user-images.githubusercontent.com/75253383/146623546-3814c535-f609-4feb-83bd-8277c885f39d.png)

### ⚙ Configurations

Title:
  - '&b欢迎来到xxxxx!'
  
Layout:
  - - '#########'
    - '#   S   #'
    - '#########'
    
PlayerInventory:
  - - '         '
    - '         '
    - '         '
    - '         '

Bindings:
  Commands:
    - 'cd'
    - 'CD'
    - 'menu'
    - 'MENU'
    - 'm'
    - 'M'
  Items:
    - 'material:clock'

Icons:
  '#':
    display:
      material: stained glass pane
      name: '&8分隔板'

  'S':
    display:
      material: Grass_Block
      name: '&axxxxx'
      lore:
            - '&7xxxxxx'
            - '&7xxxxxxxxxxxxxxxxx'
            - '&7xxxx'
            - ''
            - '&bxxxx'
            - '&dxxxxx'
    actions:
      all:
      - 'close'
      - 'command: say xxxx'

**Comment by 157946a** [comment]
将settings.yml的配置放上来看看,或者用下面的网址,把配置内容复制进去,重新复制网址放上来
https://paste.helpch.at/fipinujisa

**Comment by MCJiaoLong** [comment]
Options:
  Language: zh_CN

Loader:
  Menu-Files:
    - 'plugins/CustomMenusFolder'

Menu:
  Settings:
    Bound-Item-Interval: 0
  Icon:
    Inherit: false
    Item:
      Default-Name-Color: "&7"
      Default-Lore-Color: "&7"
      Pre-Color: false

Action:
  Inputer:
    Cancel-Words:
      - 'cancel|quit|end'
      - 'q'


RegisterCommands:
  openMenus:
    aliases: [ ]
    permission: null
    execute:
      - 'tell: &7Argument `example` Required!'
    arguments:
      example: 'open: example'

# --------------------------------------------- #
# HASH 502e960fbd1a67a361322d164d326aa1463b32df #
# --------------------------------------------- #

**Comment by 157946a** [comment]
第一个是trmenu的报错,第二个是修复漏洞bug的插件,第二个你应该去问作者,第一个你删除settings重新生成看看

**Comment by MCJiaoLong** [comment]
一个是解决了.不过我删除了所有修复漏洞的插件，第二个问题依旧没解决（核心spigot-1.16.5修复）

**Comment by 157946a** [comment]
第二个,你把bc启动后开头的信息发出来

**Comment by MCJiaoLong** [comment]
这个我发现是TrMenu插件和登陆插件的问题

**Comment by Score2** [comment]
尝试在options里加上pure-packet: false 看看

**Comment by MCJiaoLong** [comment]
还是不行
文件:
Options:
  # High, Normal, Low
  Running-Performance: Normal
  Multi-Thread: true
  Async-Load-Menus: true
  pure-packet: false

Database:
  # Local: SQLITE
  # External: SQL, MONGODB
  Method: SQLITE
  Type:
    SQLite:
      file-name: data
      table: npc
    SQL:
      host: localhost
      port: 3306
      user: root
      password: root
      database: test
      table: trmenu_user_data
    MongoDB:
      client: 'mongodb://localhost:3307'
      database: trixey
      collection: trplugins.menu
  Index:
    # UUID, USERNAME
    Player: USERNAME

Loader:
  Menu-Files:
    - 'plugins/CustomMenusFolder'

Menu:
  Settings:
    Bound-Item-Interval: 2000
  Icon:
    Inherit: false
    Item:
      Default-Name-Color: "&7"
      Default-Lore-Color: "&7"
      Pre-Color: false

Action:
  Inputer:
    Cancel-Words:
      - 'cancel|quit|end'
      - 'q'

Shortcuts:
  Offhand: [ ]
  Sneaking-Offhand: [ ]
  Right-Click-Player: [ ]
  Sneaking-Right-Click-Player: [ ]
  PlayerInventory-Border-Left: [ ]
  PlayerInventory-Border-Right: [ ]
  PlayerInventory-Border-Middle: [ ]

RegisterCommands:
  openMenus:
    aliases: [ ]
    permission: null
    execute:
      - 'tell: &7Argument `example` Required!'
    arguments:
      example: 'open: example'

**Comment by MCJiaoLong** [comment]
![QQ图片20220115142419](https://user-images.githubusercontent.com/75253383/149611704-537dae26-0ddb-497b-b552-2e7f55c79fbf.png)

**Comment by 157946a** [comment]
尝试使用watefall核心

**Comment by MCJiaoLong** [comment]
感谢你的帮助,使用Watefall核心是没问题了QWQ
