### ISSUE TITLE
[Bug]: 命令配置无法使用

### ISSUE THREAD

**Issue by AdminUndead** [InsinuateProjects/TrMenu#115]
### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

```
TrMenu Dump Information (Date: xxxx-xx-xx xx:xx:xx)

  | Server OS: xxxx
  | Server software: xxxx
  | Java version: xxxx

  | TabooLib: x.x.x
  | TrMenu: x.x.x
Installed Plugins:
  · XXXXXX - x.x.x
  · XXXXXX - x.x.x
  · XXXXXX - x.x.x
```
1.服务器版本 paper1.17.1
2.Trmenu版本 TrMenu-3.0-RC-4

### 🔍 Detailed description

```
1.服务器版本 paper1.17.1
2.Trmenu版本 TrMenu-3.0-RC-4
3.问题 在使用子icon时 第二个子图标 " - condition: 'perm *yy.helpdg'  " 以及第三,第四个condition下的actions不能使用
```
1.服务器版本 paper1.17.1
2.Trmenu版本 TrMenu-3.0-RC-4
3.问题 在使用子icon时 第二个子图标 " - condition: 'perm *yy.helpdg'  " 以及第三,第四个condition下的actions不能使用 
你可以去试试 反正我那几个图标命令就是点不了那几个子图标只能显示lore和name

### 🗄 Server log

```

```
没有日志

### ⚙ Configurations
`Title:
  - '&3&cHoly-Spirit-Island &8| &f音乐播放'

Title-Update: 30

Layout:
  - - '         '
    - ' `YYBZ` `1` `2` `3` '
    - '         '
    - '         '
    - '`ZCD`        '

Options:
  # 是否启用菜单传参功能 （默认开启）
  Arguments: true
  # 默认填充参数
  Default-Arguments: ["0"]
  # 默认布局页码
  Default-Layout: 0
  # 自由槽位
  Free-Slots:
    - '71-73'
  # 是否隐藏玩家容器
  Hide-Player-Inventory: true
  # 防频繁点击的间隔
  Min-Click-Delay: 200
  Depend-Expansions:

Events:
  # 开启菜单
  Open:
    - 'refresh'

Bindings:
  Commands:
    - 'yy'

Icons:
  '#':
    update: 5
    display:
      material: 'BARRIER'
      name: 
        - '&8[&3分割线&8]'
      lore:
        - - '&7&f官方群号：&d» 0'
          - '&2&lLv.%player_level% %player_name%'
          - '&a&l称号&f: &B%alonsotags_tag_tab%'
          - '&a&l等级&f: &B%vault_group%'
          - '&a&l金币&f: &e%vault_eco_balance%'
    actions:
      all: 
        - 'sound: BLOCK_NOTE_BLOCK_BIT-1-0'
        - 'refresh'
  'ZCD':
    update: 5
    display:
      material: 'head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7ImlkIjoiOWQ0NzI0NDhkNTczNGQ0ODgzZDNmMTU2N2Y0NDcyZjAiLCJ0eXBlIjoiU0tJTiIsInVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGVmZjcyNzE1ZTYwMzJlOTBmNTBhMzhmNDg5MjUyOTQ5M2M5ZjU1NWI5YWYwZDVlNzdhNmZhNWNkZGZmM2NkMiIsInByb2ZpbGVJZCI6IjdmYWI1NWQyOTM4NzQ1ZjQ5NGFhOGVlYjMxMmY1NjRiIiwidGV4dHVyZUlkIjoiNGVmZjcyNzE1ZTYwMzJlOTBmNTBhMzhmNDg5MjUyOTQ5M2M5ZjU1NWI5YWYwZDVlNzdhNmZhNWNkZGZmM2NkMiJ9fSwic2tpbiI6eyJpZCI6IjlkNDcyNDQ4ZDU3MzRkNDg4M2QzZjE1NjdmNDQ3MmYwIiwidHlwZSI6IlNLSU4iLCJ1cmwiOiJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzRlZmY3MjcxNWU2MDMyZTkwZjUwYTM4ZjQ4OTI1Mjk0OTNjOWY1NTViOWFmMGQ1ZTc3YTZmYTVjZGRmZjNjZDIiLCJwcm9maWxlSWQiOiI3ZmFiNTVkMjkzODc0NWY0OTRhYThlZWIzMTJmNTY0YiIsInRleHR1cmVJZCI6IjRlZmY3MjcxNWU2MDMyZTkwZjUwYTM4ZjQ4OTI1Mjk0OTNjOWY1NTViOWFmMGQ1ZTc3YTZmYTVjZGRmZjNjZDIifSwiY2FwZSI6bnVsbH0='
      name: 
        - '&8[&3主菜单&8]'
      lore:
        - - '&7&f官方群号：&d» 0'
          - '&7点击返回主菜单'
    actions:
      all: 
        - 'sound: BLOCK_BEEHIVE_EXIT'
        - 'refresh'
      left:
        - 'open: Example {delay=10}'
  'YYBZ':
    update: 1
    refresh: 1
    display:
      material: 'head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTdlZTQyMTE2MDA0NWI5NWY3ODk5NTY4Y2E5OWIyMDA5YjQxMzdhZTFkZjMyYTc2OTU3Mjk3Y2FjNDA3YmI4MyJ9fX0='
      name: 
        - '&8[&b&n音乐使用帮助&8]'
      lore:
        - - ' '
          - '&7请右键当前图标选择一个需要查看的帮助类型'
          - '&2[&b左键&2]>>&a确认选择查看帮助'
          - ' '
          - '&f当前选择>> 查看&3&l主菜单&f帮助'
          - '&7查看&3&l播放&7帮助'
          - '&7查看&3&l点歌&7帮助'
          - '&7查看&3&l搜索&7帮助'
          - '&7查看&3&l歌单&7帮助'
    actions:
      all: 
        - 'sound: BLOCK_BEEHIVE_EXIT'
        - 'refresh'
      left:
        - 'command: zm help'
      right:
        - 'console: lp user %player_name% permission set yy.helpbf'
        - 'refresh'
    icons:
      - condition: 'perm *yy.helpbf'
        display:
          material: 'head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDQxZGZiMzAxYzA0NzAxODdmOTA3ODE0ZjU5NDNlYmRiOGI2YTEyNzgzMzMzNjlhYTM1Mjk5Y2UzOTQwOTI3NyJ9fX0='
          name: 
            - '&8[&b&n音乐使用帮助&8]'
          lore:
            - - ' '
              - '&7请右键当前图标选择一个需要查看的帮助类型'
              - '&2[&b左键&2]>>&a确认选择查看帮助'
              - ' '
              - '&7查看&3&l主菜单&7帮助'
              - '&f当前选择>> 查看&3&l播放&f帮助'
              - '&7查看&3&l点歌&7帮助'
              - '&7查看&3&l搜索&7帮助'
              - '&7查看&3&l歌单&7帮助'
        actions:
          all: 
            - 'sound: BLOCK_BEEHIVE_EXIT'
            - 'refresh'
          left:
            - 'command: zm help play'
          right:
            - 'console: lp user %player_name% permission unset yy.helpbf'
            - 'refresh'
            - 'console: lp user %player_name% permission set yy.helpdg'
            - 'refresh'

      - condition: 'perm *yy.helpdg'
        display:
          material: 'head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWYwMGY1N2RkNjlkODFjZWEwNzZkZDFjZDJkNzAxNjlhZTkxY2JjYjQ2YzBmMWM3MTJiZjBiZGU4YmY1NDE4MSJ9fX0='
          name:
            - '&8[&b&n音乐使用帮助&8]'
          lore:
            - - ' '
              - '&7请右键当前图标选择一个需要查看的帮助类型'
              - '&2[&b左键&2]>>&a确认选择查看帮助'
              - ' '
              - '&7查看&3&l主菜单&7帮助'
              - '&7查看&3&l播放&7帮助'
              - '&f当前选择>> 查看&3&l点歌&f帮助'
              - '&7查看&3&l搜索&7帮助'
              - '&7查看&3&l歌单&7帮助'
          actions:
            all: 
              - 'sound: BLOCK_BEEHIVE_EXIT'
              - 'refresh'
            left:
              - 'command: zm help play'
            right:
              - 'console: lp user %player_name% permission unset yy.helpbf'
              - 'refresh'
              - 'console: lp user %player_name% permission set yy.helpdg'
              - 'refresh'

      - condition: 'perm *yy.helpss'
        display:
          material: 'head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGM4ZGJlNmIzMTkwMTA2Yjg3NDI2MWUzNDEwNzIyM2VlOTg1ZTAzMDE2MzcxNjQ3Y2YxMGVmNDQwNGMyOGQ3MiJ9fX0='
          name:
            - '&8[&b&n音乐使用帮助&8]'
          lore:
            - - ' '
              - '&7请右键当前图标选择一个需要查看的帮助类型'
              - '&2[&b左键&2]>>&a确认选择查看帮助'
              - ' '
              - '&7查看&3&l主菜单&7帮助'
              - '&7查看&3&l播放&7帮助'
              - '&7查看&3&l点歌&7帮助'
              - '&f当前选择>> 查看&3&l搜索&f帮助'
              - '&7查看&3&l歌单&7帮助'
          actions:
            all: 
              - 'sound: BLOCK_BEEHIVE_EXIT'
              - 'refresh'
            left:
              - 'command: zm help search'
            right:
              - 'console: lp user %player_name% permission unset yy.helpss'
              - 'refresh'
              - 'console: lp user %player_name% permission set yy.helpgd'
              - 'refresh'

      - condition: 'perm *yy.helpgd'
        display:
          material: 'head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGM4ZGJlNmIzMTkwMTA2Yjg3NDI2MWUzNDEwNzIyM2VlOTg1ZTAzMDE2MzcxNjQ3Y2YxMGVmNDQwNGMyOGQ3MiJ9fX0='
          name:
            - '&8[&b&n音乐使用帮助&8]'
          lore:
            - - ' '
              - '&7请右键当前图标选择一个需要查看的帮助类型'
              - '&2[&b左键&2]>>&a确认选择查看帮助'
              - ' '
              - '&7查看&3&l主菜单&7帮助'
              - '&7查看&3&l播放&7帮助'
              - '&7查看&3&l点歌&7帮助'
              - '&7查看&3&l搜索&7帮助'
              - '&f当前选择>> 查看&3&l歌单&f帮助'
          actions:
            all: 
              - 'sound: BLOCK_BEEHIVE_EXIT'
              - 'refresh'
            left:
              - 'command: zm help playlist'
            right:
              - 'console: lp user %player_name% permission unset yy.helpgd'
              - 'refresh'`

**Comment by 157946a** [comment]
把你的配置上传到这里,方便查看格式
https://paste.helpch.at/fipinujisa

**Comment by AdminUndead** [comment]
解决问题了打扰了

**Comment by AdminUndead** [comment]
原来是格式问题
