### ISSUE TITLE
[Feature]: add support for the Skulls plugin

### ISSUE THREAD

**Issue by Zarkness** [InsinuateProjects/TrMenu#120]
### 📚 Have you checked the Wiki

- [X] I have checked the Wiki and determined that this feature does not exist.

### 🔗 Is there a duplicate issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 🔍 Detailed description

Add support for the skulls plugin which is like the headdatabase but free the way to add a head through the skulls plugin could be skulls:<id of the head> or sdb:<id of the head>.

plugin link in spigot: https://www.spigotmc.org/resources/skulls-the-ultimate-head-database.90098/

wiki link: https://docs.tweetzy.ca/official-plugins/skulls#developer-api-methods

**Comment by 157946a** [comment]
This plugin has always been supported, starting from 1.
