### ISSUE TITLE
[Bug]: 新版本3.1.1，不指定动作名称时，无法默认使用Kether

### ISSUE THREAD

**Issue by Ling556** [InsinuateProjects/TrMenu#134]
### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

```
TrMenu Dump Information (Date: xxxx-xx-xx xx:xx:xx)

  | Server OS: xxxx
  | Server software: xxxx
  | Java version: xxxx

  | TabooLib: x.x.x
  | TrMenu: x.x.x
Installed Plugins:
  · XXXXXX - x.x.x
  · XXXXXX - x.x.x
  · XXXXXX - x.x.x
```

### 🔍 Detailed description

新版本3.1.1，不指定动作名称时，无法默认使用Kether
执行时，提示未知音效

**Comment by 157946a** [comment]
举例说明

**Comment by Score2** [comment]
Fixed in https://github.com/TrMenu/TrMenu/pull/360
