### ISSUE TITLE
[Bug]: 在群组服中正版玩家的皮肤头颅无法正常显示

### ISSUE THREAD

**Issue by Dirt233** [InsinuateProjects/TrMenu#139]
### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

TrMenu Dump Information (Date: 2022-02-02 15:31:23)

| Server OS: Windows 10 amd64 10.0
| Server software: git-Paper-1620 (MC: 1.12.2) (1.12.2-R0.1-SNAPSHOT)
| Java version: 1.8.0_311

| TrMenu: 3.1.1
Installed Plugins: 
· AlwaysDay - 2.2.8 (0 KB)
· AnimationLib - 1.7.0 (0 KB)
· BBSToper - 3.6.7 (0 KB)
· CashCode - 1.7 (0 KB)
· ChairStairs - 1.1 (0 KB)
· Citizens - 2.0.27-SNAPSHOT (build 2302) (0 KB)
· CommandNPC - 1.9.1 (0 KB)
· CommandPrompter - 0.1.19 (0 KB)
· DeluxeJoin - 2.9.2 (0 KB)
· DeluxeMenus - 1.13.3-Release (0 KB)
· FarmProtect - 1.9.0 (0 KB)
· GadgetsMenu - 5.0.6 (0 KB)
· Helper - 1.0.0 (0 KB)
· HolographicDisplays - 3.0.0-SNAPSHOT (0 KB)
· Images - 2.2.3 (0 KB)
· ItemJoin - 5.2.1-RELEASE-b678 (0 KB)
· LiteBans - 2.7.5 (0 KB)
· LiteBoard - 5.2.4 (0 KB)
· LiteInvitation - 1.4.3-SNAPSHOT (0 KB)
· LobbyLevel - 1.0-Revamp (0 KB)
· LobbyPresents - 4.3 (0 KB)
· LuckPerms - 5.3.64 (0 KB)
· Mczf - 1.0.0-b20 (0 KB)
· MiaoChat - 2.0.0-git-be66b3b9a0c8a8f4a1ccc360671efededb8bdce1 (0 KB)
· MyCommand - 5.7.1 (0 KB)
· NametagEdit - 4.4.10 (0 KB)
· NickNamer - 3.18.6-SNAPSHOT (0 KB)
· NoJoinQuitMessage - 2.3.3 (0 KB)
· NoRain - 1.6 (0 KB)
· PacketListenerApi - 3.7.9-SNAPSHOT (0 KB)
· PlaceholderAPI - 2.11.1 (0 KB)
· PlayerBalancerAddon - 2.3.1-SNAPSHOT (0 KB)
· PlayerCommands - 1.0.0 (0 KB)
· PlayerHider - 1.4 (0 KB)
· PlayerMention - 2.0 (0 KB)
· PlayerPoints - 2.1.5-SNAPSHOT (0 KB)
· ProtocolLib - 4.6.0 (0 KB)
· SQLibrary - 7.1 (0 KB)
· SimpleFly - 3.0 (0 KB)
· SkinsRestorer - 14.1.10 (0 KB)
· StopFallDamage - 1.0 (0 KB)
· SuperAntiChat - 1.0.0 (0 KB)
· TigerReports - 4.13.1 (0 KB)
· TpLogin - 3.1 (0 KB)
· TrMenu - 3.1.1 (0 KB)
· UltimateBossBar - 1.5.2 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· VipSystem - 4.13 (0 KB)
· Void2Spawn - 1.1.0 (0 KB)
· WorldBorder - 1.8.7 (0 KB)
· WorldEdit - 6.1.9;caf0ad9 (0 KB)
· XConomy - 2.11.1 (0 KB)
· Yum - 2.9.5-git-18dc99e78ee6c087da72f944be32e90e5c93b3a5 (0 KB)

### 🔍 Detailed description

就是这样一个问题，在安装了SkinsRestorer之后，依然无法正常显示玩家头颅
在单子服中实验是正常显示的

### 🗄 Server log

trm reload
[15:34:02 INFO]: [TrMenu] 良好 | 2 个菜单已加载 (36 ms)

null

### ⚙ Configurations

l:
    display: 
      material: head:%player_name%
      name: '&e%nicknamer_nickname%'
      lore:
        - 
        - '&b职位&f: &r%luckperms_prefix%'
        - '&b会员&f: &r%vipsystem_vip%'
        - ' &7等级: &f[%lobbylevel_level%&f]'
        - ' &7进度: &7%lobbylevel_exp%&7/&f%lobbylevel_totalexp%'
        - ' &7[&a%lobbylevel_JinDu%&7]'
        - '&b会员等级: &e%vipsystem_vip%'
        - '&b会员剩余: &e%vipsystem_left%'
        - '&b神秘之尘: &e%gadgetsmenu_mystery_dust%'
        - '&b奖励箱个数: &e%gadgetsmenu_mystery_boxes%'
        - '&b注册时间&f: &r%player_first_played_formatted%'
        - '&b上次登录时间&f: &r%player_last_played_formatted%'

**Comment by 157946a** [comment]
检查子服是否都开了spigot.yml的bc开关,是就删除子服即可,不是bug

**Comment by Dirt233** [comment]
@157946a 什么叫删除子服

**Comment by Dirt233** [comment]
@157946a 删除就不可能能进得去的

**Comment by 157946a** [comment]
我是指删除子服的skin
