### ISSUE TITLE
[Bug]: 1.8的title无法正常使用

### ISSUE THREAD

**Issue by Dirt233** [InsinuateProjects/TrMenu#140]
### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

TrMenu Dump Information (Date: 2022-02-02 15:36:45)

| Server OS: Windows 10 amd64 10.0
| Server software: git-PaperSpigot-445 (MC: 1.8.8) (1.8.8-R0.1-SNAPSHOT)
| Java version: 1.8.0_311

| TrMenu: 3.1.1
Installed Plugins: 
· LuckPerms - 5.3.64 (0 KB)
· PlaceholderAPI - 2.11.1 (0 KB)
· SkinsRestorer - 14.1.10 (0 KB)
· TrMenu - 3.1.1 (0 KB)

### 🔍 Detailed description

1.8动作类型title无法正常显示title

### 🗄 Server log

trm reload
[15:37:52 INFO]: [TrMenu] 良好 | 2 个菜单已加载 (16 ms)

### ⚙ Configurations

actions:
    all:
       - 'title: Hello'

**Comment by Score2** [comment]
如有报错，请提供

**Comment by Dirt233** [comment]
没有报错

**Comment by Dirt233** [comment]
这里提供个阿里云盘的演示图片的链接
[](https://www.aliyundrive.com/s/At3c3Wsu288)
这个

**Comment by Dirt233** [comment]
https://www.aliyundrive.com/s/At3c3Wsu288

**Comment by 157946a** [comment]
上传服务器核心,以方便浮现问题

**Comment by Dirt233** [comment]
链接：https://pan.baidu.com/s/1dtTJwMb9Uxp6z8Dsb-l8Tw?pwd=fa0y 
提取码：fa0y

**Comment by 157946a** [comment]
尝试使用最新
