### ISSUE TITLE
[Bug]: Inventory not flush due to TrMenu or TabooLib packet related things on version 1.17.1

### ISSUE THREAD

**Issue by Niocho** [InsinuateProjects/TrMenu#153]
### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

This issue cannot be addressed with TrMenu's dump log.

### 🔍 Detailed description

This issue has been solved in version 1.16.4 in ISSUE #54  . It's been confirmed happening in version 1.17.1 again.

Player sometimes pick things up with player' inventory not flushed. The inventory stays the previous state which seems like the item stack not joined into the inventory. In fact, the item stack has been placed in the player inventory logically in the server. Player can solve this problem using re-join server or other methods to require new inventory packet to client in order to solve this bug.

### 🗄 Server log

```
No log can be found related to this bug.
```

### ⚙ Configurations

Possibly related funcion name: `hide-player-inventory`

**Comment by 157946a** [comment]
Use latest build

**Comment by 157946a** [comment]
Upload URL after using trmenu debug dump command
