### ISSUE TITLE
[Bug]: Does not detect well when a variable is &2True or &cFalse

### ISSUE THREAD

**Issue by Zarkness** [InsinuateProjects/TrMenu#154]
### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

```
TrMenu Dump Information (Date: 2022-03-04 21:29:34)

| Server OS: Linux amd64 5.4.0-100-generic
| Server software: git-Paper-186 (MC: 1.18.1) (1.18.1-R0.1-SNAPSHOT)
| Java version: 17.0.1

| TrMenu: 3.1.4
Installed Plugins: 
· CMILib - 1.1.1.1 (0 KB)
· Citizens - 2.0.29-SNAPSHOT (build 2443) (0 KB)
· CommandTool - 2.1.0 (0 KB)
· CyberLevels - 0.4.3 (0 KB)
· DecentHolograms - 2.2.7 (0 KB)
· DeluxeMenus - 1.13.4-DEV-119 (0 KB)
· FastAsyncWorldEdit - 2.0.2-SNAPSHOT-89;7da993d (0 KB)
· HeadBlocks - 1.5.9 (0 KB)
· HideItem - 4.1.1 (0 KB)
· HolographicDisplays - 3.0.0-SNAPSHOT (0 KB)
· ItemJoin - 5.2.3-RELEASE-b789 (0 KB)
· Jobs - 5.0.1.4 (0 KB)
· LibertyBans - 1.0.0 (0 KB)
· LuckPerms - 5.4.1 (0 KB)
· Maintenance - 4.0.0-SNAPSHOT (0 KB)
· MaintenanceAddon - 1.1.0 (0 KB)
· Multiverse-Core - 2.5.0-b727 (0 KB)
· NoDamageNoHunger - 1.1 (0 KB)
· NoRain - 1.4.1 (0 KB)
· PhysicsControl - Beta-5 (0 KB)
· PlaceholderAPI - 2.11.1 (0 KB)
· ProtocolLib - 4.8.0-SNAPSHOT-b540 (0 KB)
· SIR - 2.0-R0 (0 KB)
· SkinsRestorer - 14.1.10 (0 KB)
· Skulls - 2.9.0 (0 KB)
· TAB - 3.1.0-SNAPSHOT (0 KB)
· TrMenu - 3.1.4 (0 KB)
· UltimateAutoRestart - Build 51e (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· ViaBackwards - 4.1.1 (0 KB)
· ViaRewind - 2.0.2 (0 KB)
· ViaVersion - 4.1.1 (0 KB)
· VoidGen - 2.2.1 (0 KB)
· VoidTeleport - 2.4.1 (0 KB)
· WorldGuard - 7.0.6+1cff55f (0 KB)
· ajParkour - 2.12.10 (0 KB)
· spark - 1.8.0 (0 KB)
```

### 🔍 Detailed description

When I make a condition 
$ vars("%jobsr_user_isin_Miner%") == "True" or 
$ vars("%pinger_online_online_ip:port%") == "Online"
In the config of the placeholderapi or plugin is usually &2True or &2Online it does not detect it even if I put "&2True" or "&2Online" and I have to go to the plugin config either the placeholderapi or any other and put True or Online without the color code if it does not detect it.

**Comment by Zarkness** [comment]
Another thing to put commands like /jobs or /warp to open a menu if I put to run the action /warp food for it to work I have to put to run from console putting console: warp food %player_name% and the same with any command that has subcommands and want the command to open the menu and not with its subcommands.

**Comment by 157946a** [comment]
Have you tried the color symbol of §? I had a similar problem when I used the & symbol in js, mine is displayed directly, yours may be judged as a string

**Comment by 157946a** [comment]
Have you tried changing the command, such as warps

**Comment by Zarkness** [comment]
> Have you tried changing the command, such as warps

I tried all the ways I could think of and nothing, I want it to open the menu with the warp and warps commands, I don't like that I put /warp and it doesn't open any menu and that it sends me a message with all the warps.

**Comment by Zarkness** [comment]
> Have you tried the color symbol of §? I had a similar problem when I used the & symbol in js, mine is displayed directly, yours may be judged as a string

No I haven't tried it but there should be some way that if in the menu I put True or Online even if the other plugin has &2True or whatever it detects that True even if it is &{#ffffffff}True in the other plugin.

**Comment by 157946a** [comment]
It has been verified that the & symbol cannot be replaced in js, only §
