### ISSUE TITLE
[Bug]: trmenu 3.1.8自带配置文件的shop-example的问题

### ISSUE THREAD

**Issue by yuankun1** [InsinuateProjects/TrMenu#157]
### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

TrMenu Dump Information (Date: 2022-03-09 02:49:08)

| Server OS: Windows Server 2019 amd64 10.0
| Server software: git-Mohist-1.12.2-309 (MC: 1.12.2) (1.12.2-R0.1-SNAPSHOT)
| Java version: 1.8.0_291

| TrMenu: 3.1.8
Installed Plugins: 
· AntiBuild - 1.3.2-SNAPSHOT (0 KB)
· AntiExplosion - 1.0.1 (0 KB)
· AsyncKeepAlive - 0.3 (0 KB)
· AudioBuffer - 1.0.3 (0 KB)
· AuthMe - 5.6.0-SNAPSHOT-b2481 (0 KB)
· BanIt - 1.1.0 (0 KB)
· BeatPoke - 1.0 (0 KB)
· BlockParticles - 1.11.1-RELEASE (0 KB)
· CMI - 9.1.1.1 (0 KB)
· CMILib - 1.1.2.0 (0 KB)
· CombatPower - 1.0.3-SNAPSHOT (0 KB)
· CoreProtect - 2.14.4 (0 KB)
· CowSuperJoin - 1.71 (0 KB)
· CrazyAuctionsPlus - 1.2.0.1 (0 KB)
· CrazyCrates - 1.10.1-RELEASE (0 KB)
· CtOnlineReward - 0.1.7 (0 KB)
· CustomBossHealth - ULTX (0 KB)
· DomainAudio - 1.0.0 (0 KB)
· DragonCore - 2.5.4 (0 KB)
· DreamChest - 1.0.4-SNAPSHOT (0 KB)
· EpicPluginLib - 1.6.6 (0 KB)
· EscapeLag - 2.1.0-b557 (0 KB)
· FastAsyncWorldEdit - ${version} (0 KB)
· FileListener - 1.0.0 (0 KB)
· Fixer - 1.6.8-SNAPSHOT (0 KB)
· HeroAction - 4.0 (0 KB)
· IllegalStack - 2.4.2a (0 KB)
· LegendarySpawnExpand - 1.2 (0 KB)
· LiteInvitation - 1.4.5-SNAPSHOT (0 KB)
· LiteSignIn - 1.4.0 (0 KB)
· LuckPerms - 5.2.76 (0 KB)
· MinePay - Release 2.6.9 (0 KB)
· MiniMOTD - 2.0.4 (0 KB)
· MobFarmManager - 2.0.2.1 (0 KB)
· Multiverse-Core - 2.5.0-b727 (0 KB)
· Multiverse-Patches - 1.0.0-SNAPSHOT (0 KB)
· NBTAPI - 2.8.0 (0 KB)
· NyEconomy - 1.4.5-SNAPSHOT (0 KB)
· NyPhysical - 1.2.6-SNAPSHOT (0 KB)
· PTweaks - 6.0.16-b13 (0 KB)
· PixelExtras - 1.5.1-SNAPSHOT (0 KB)
· PixelVip - 3.0.3 (0 KB)
· PixelmonEssentials - 1.3.1-8.0.2-public (0 KB)
· PixelmonExpSpring - 1.3-SNAPSHOT (0 KB)
· PixelmonPvp - 2.3.1.0-SNAPSHOT (0 KB)
· PlaceholderAPI - 2.10.9 (0 KB)
· PlayMoreSounds - 3.3.0 (0 KB)
· PlayerPoints - 3.0.3 (0 KB)
· PlayerTitle - 2.10.4 (0 KB)
· PlotSquared - 19.12.10-b4c257b-788 (0 KB)
· PlugMan - 2.2.5 (0 KB)
· PokeBoss - 3.6 (0 KB)
· PokeBreedLimit - 1.1 (0 KB)
· PokeDexLimit - 1.0 (0 KB)
· PokeDialogue - 1.2 (0 KB)
· PokeEvo - 1.0-SNAPSHOT (0 KB)
· PokeExplore - 1.0 (0 KB)
· PokeMessage - 1.0 (0 KB)
· PokeMsg - 2.1-SNAPSHOT (0 KB)
· PokePlate - 1.4.5 (0 KB)
· PokeStar - 1.1.3-SNAPSHOT (0 KB)
· PokeTaskPlugin - 2.1.9-RELEASE (0 KB)
· PokeTools - 1.1.4-SNAPSHOT (0 KB)
· PokemonAPI - 3.2.1.0-SNAPSHOT (0 KB)
· PokemonHuntArean - 1.6.2-SNAPSHOT (0 KB)
· PokemonInfo - 1.9.8-SNAPSHOT (0 KB)
· PokemonJianding - 1.0 (0 KB)
· PokemonMoreExp - 1.0 (0 KB)
· PokemonSkin - 1.0 (0 KB)
· PokemonTrain - 1.0 (0 KB)
· ProtocolLib - 4.7.0 (0 KB)
· PuerkasMarriage - 1.9.5-BETA (0 KB)
· QuickShop - 2.3.1-git-8edb488ab24519236553cabd943e946c6f223b02 (0 KB)
· RandomGrowth - 1.0.0-SNAPSHOT (0 KB)
· SpawnLegTime - 2.0 (0 KB)
· SuperTrailsPro - v1.2.17 (0 KB)
· TXZ - 1.4.6-SNAPSHOT (0 KB)
· TimedWorld - 1.1 (0 KB)
· TitleDomain - 1.2.1 (0 KB)
· TrChat - 1.90-R3 (0 KB)
· TrMenu - 3.1.8 (0 KB)
· TradeBlackList - 1.1 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· VeinMiner - 1.11.3 (0 KB)
· VoidGen - 2.0 (0 KB)
· WorldBorder - 1.8.7 (0 KB)
· WorldEdit - 6.1.9-0.3-SNAPSHOT (0 KB)
· XConomy - 2.11.4 (0 KB)
· XinxinApi - 1.1.0-SNAPSHOT (0 KB)
· XinxinPokeConnection - 1.0.1-SNAPSHOT (0 KB)
· YukiNoaAPI - 1.0.0 (0 KB)

### 🔍 Detailed description

```
1. shop-example文件里的Shop-Handler-Purchase.yml的配置文件
trplugins.menu改成menu/或者open 
2. 打开Shop-Ores菜单进入购买和选择数量
3.在按E或者ESC键 他会弹回到Shop-Ores里面的东西可以偷或者挪动

### 🗄 Server log

无报错

### ⚙ Configurations

Title:
  - 'Purchasing'

Layout:
  - '########<'
  - '|       |'
  - '| - X + |'
  - '|       |'
  - '####*####'

# {0}         {1}         {2}           {3}
# {fromMenu} {itemName} {singlePrice} {amount}
Events:
  Open:
    - 'reset'
  Close:
    - 'trplugins.menu: {0}'
    - 'del-args'

**Comment by yuankun1** [comment]
这个是插件毕竟少的https://paste.helpch.at/fosagiquhu
这个只会直接关闭菜单 不会返回到Shop-Ores菜单

**Comment by yuankun1** [comment]
Shop-Ores配置文件
  '0':
    display:
      material: coal ore
      lore:
        - ''
        - '&8▪ &7Purchase: &e$20.0'
        - '&8▪ &7Sell: &2$3.5'
        - ''
        - '&e➥ &6Left &8| &6Purchase'
        - '&e➥ &6Right &8| &6Sell'
    actions:
      all:
        - 'sound: UI_BUTTON_CLICK-1-2'
      left:
        - 'trplugins.menu: Shop-Handler-Purchase Shop-Ores COAL_ORE 20 1 64'
      right:
        - 'trplugins.menu: Shop-Handler-Sell Shop-Ores COAL_ORE 3.5 1 64'
       这样会提示未知音效
把trplugins.menu改成menu就不会有什么问题

**Comment by 157946a** [comment]
trplugins.menu改成menu或者open即可,维护者替换的时候不小心替换了这里的
