### ISSUE TITLE
怎么判断两个args相等

### ISSUE THREAD

**Issue by xingguanglang** [InsinuateProjects/TrMenu#16]
如下,打开菜单时已经设置了一个String参数 {0}，在执行过程中游另一个String参数{1}（或者单纯的String）,如何实现判断这两个值相等，如果相等执行语句A,不等执行语句B

  'B':
    display:
      material: white stained glas pane
      name: '&b{0}'
      lore: 
      - '&e花费4000金币和16个命令方块'
      - '&e购买一个领地的飞行权限'
    action:
      all:
      - condition: 'js: {0}=={1}'      ？？？？？？？？？？？？？？？？？？？？？？？？？？？？？
        actions: 
        - 'tell: [菜单/领地设置]{0}飞行权限已设置'
        deny:
        - 'tell: [菜单/领地设置]&4金钱不足'

**Comment by 157946a** [comment]
这里是反馈问题的,不是问问题的地方

**Comment by Super-10** [comment]
> 如下,打开菜单时已经设置了一个String参数 {0}，在执行过程中游另一个String参数{1}（或者单纯的String）,如何实现判断这两个值相等，如果相等执行语句A,不等执行语句B
> 
> 'B':
> display:
> material: white stained glas pane
> name: '&b{0}'
> lore:
> - '&e花费4000金币和16个命令方块'
> - '&e购买一个领地的飞行权限'
> action:
> all:
> - condition: 'js: {0}=={1}' ？？？？？？？？？？？？？？？？？？？？？？？？？？？？？
> actions:
> - 'tell: [菜单/领地设置]{0}飞行权限已设置'
> deny:
> - 'tell: [菜单/领地设置]&4金钱不足'

js: X==x ? "false" : "true"
