### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by fenglanxi** [InsinuateProjects/TrMenu#164]
### 🚀 Have you tried the latest version

- [X] I have updated TrMenu to the latest version and the same bug is reproduced.

### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

TrMenu Dump Information (Date: 2022-03-16 06:09:47)

| Server OS: Linux amd64 4.18.0-348.7.1.el8_5.x86_64
| Server software: git-Purpur-1428 (MC: 1.17.1) (1.17.1-R0.1-SNAPSHOT)
| Java version: 17.0.2

| TrMenu: 3.1.9
Installed Plugins: 
· Brewery - 3.1 (0 KB)
· BungeeTabListPlus - 3.4.4 (0 KB)
· CMI - 9.1.3.0 (0 KB)
· CMILib - 1.1.2.1 (0 KB)
· Citizens - 2.0.29-SNAPSHOT (build 2457) (0 KB)
· DeluxeBazaar - 3.2 (0 KB)
· Interactions - 1.25.2 (0 KB)
· InventoryRollbackPlus - 1.6.5 (0 KB)
· ItemsAdder - 3.0.2 (0 KB)
· LibsDisguises - 10.0.27-SNAPSHOT (0 KB)
· LightAPI - bukkit-5.1.0 (build SNAPSHOT) (0 KB)
· LoneLibs - 1.0.18 (0 KB)
· LuckPerms - 5.4.9 (0 KB)
· McMmoView - 1.0.2 (0 KB)
· MiaoBoard - 2.5.1-git-3f193bbf460541fb71a29af94bca98f8317e2ea7 (0 KB)
· MysqlPlayerDataBridge - 4.1.0 (0 KB)
· PlaceholderAPI - 2.11.1 (0 KB)
· PlayerPoints - 3.2.0 (0 KB)
· PlugManX - 2.3.0 (0 KB)
· Pouvoir - 1.2.7 (0 KB)
· ProtocolLib - 5.0.0-SNAPSHOT-b551 (0 KB)
· Quests - 4.2.2-b303 (0 KB)
· ResourcePackBroadcast - 1.0.4 (0 KB)
· ScreenEffects - 1.0.13 (0 KB)
· SkinsRestorer - 14.1.13 (0 KB)
· TrChat - 1.90-R8 (0 KB)
· TrMenu - 3.1.9 (0 KB)
· TradeMe - 6.1.1.1 (0 KB)
· Vault - 1.7.3-CMI (0 KB)
· ViaVersion - 4.2.1 (0 KB)
· mcMMO - 2.1.210-SNAPSHOT (0 KB)

### 🔍 Detailed description

版本3.19插件可以加载菜单都正常，但是过一会就输入不了任何指令和在聊天框说话，再次重启刚开始是可以的过一会就不行了

### 🗄 Server log

```

```

### ⚙ Configurations

```

```

**Comment by Score2** [comment]
请自行排除其它插件因素
