### ISSUE TITLE
[问题]: 与插件FartherViewDistance冲突，无法使用菜单

### ISSUE THREAD

**Issue by hooll** [InsinuateProjects/TrMenu#169]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

TrMenu Dump Information (Date: 2022-03-19 22:47:16)

| Server OS: Windows 10 amd64 10.0
| Server software: git-Purpur-1597 (MC: 1.18.2) (1.18.2-R0.1-SNAPSHOT)
| Java version: 17.0.1

| TrMenu: 3.1.9
Installed Plugins: 
· CMI - 9.1.3.1 (0 KB)
· CMIEInjector - 1.0.2.3 (0 KB)
· CMILib - 1.1.2.3 (0 KB)
· ConsoleSpamFix - 1.9.0 (0 KB)
· CoreProtect - 21.1 (0 KB)
· FartherViewDistance - 9.1.2 (0 KB)
· Lores - 1.4.1 (0 KB)
· Multiverse-Core - 4.3.1-b861 (0 KB)
· NoPlugins - 8.1 (0 KB)
· NoSpawnChunks - 2.0.1-SNAPSHOT-b148 (0 KB)
· PlaceholderAPI - 2.11.1 (0 KB)
· PlugManX - 2.2.7 (0 KB)
· ProtocolLib - 4.8.0 (0 KB)
· TrChat - 1.90-R8 (0 KB)
· TrMenu - 3.1.9 (0 KB)
· Vault - 1.7.3-CMI (0 KB)

### 🔍 详细的描述

```
1. 安装以发包提高视距的插件FartherViewDistance后会出现无法使用菜单，只能打开一次菜单
```

### 🗄 服务端日志

```

```

### ⚙ 配置文件

```

```

**Comment by patatoplugin** [comment]
我测试了一下，也有一样的问题，加入fatherviewdistance后菜单无法正常使用
插件链接:https://www.spigotmc.org/resources/fartherviewdistance.84950/updates

**Comment by Score2** [comment]
该插件将playerConnection.channel 字段名称进行了更改，导致依赖该字段的taboolib无法获取到该字段而出现该报错

**Comment by Score2** [comment]
尝试更新到最新版本fvd来验证是否已解决
