### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by q121314572** [InsinuateProjects/TrMenu#170]
### 🚀 Have you tried the latest version

- [X] I have updated TrMenu to the latest version and the same bug is reproduced.

### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

Oraxen的物品材质无法正常加载
不管是用mats 还是 material 都不行  1.17以上都无法正常加载
oraxen:xxxx

### 🔍 Detailed description

```
1. ...
2. ...
3. ...
```

### 🗄 Server log

```

```

### ⚙ Configurations

 display:
      mats: 'oraxen:alert'
      name: '&2&l%player_name%'

**Comment by Adriianh** [comment]
Have you tried "source:ORAXEN:(item)"?

**Comment by Adriianh** [comment]
> 

I'm using it and it works fine
