### ISSUE TITLE
[Feature]:  求作者大大，修复一下，Arclight服务端和墨端，插件能加载，菜单加载不了！

### ISSUE THREAD

**Issue by Dawn2329** [InsinuateProjects/TrMenu#178]
### 📚 Have you checked the Wiki

- [X] I have checked the Wiki and determined that this feature does not exist.

### 🔗 Is there a duplicate issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 🔍 Detailed description

```
1. ...
2. ...
3. ...
```
<html>
<body>

求作者大大，修复一下，Arclight服务端和墨端，插件能加载，菜单加载不了！
--

</body>
</html>

### ⚙ Configurations

```

```
<html>
<body>

求作者大大，修复一下，Arclight服务端和墨端，插件能加载，菜单加载不了！
--

</body>
</html>

**Comment by Score2** [comment]
请根据issue模板提示要求重新发起一个issue，否则不受理
