### ISSUE TITLE
[Bug]:无法在paper-1.8.8-445上正常运作

### ISSUE THREAD

**Issue by QianCraft** [InsinuateProjects/TrMenu#183]
### 🚀 Have you tried the latest version

- [X] I have updated TrMenu to the latest version and the same bug is reproduced.

### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

1. 插件无法在paper-1.8.8-445上正常运作 输入/pl 插件显示红色 测试过 换成低版本paper可以正常运作

### 🔍 Detailed description

```
1. 插件无法在paper-1.8.8-445上正常运作 输入/pl 插件显示红色 测试过 换成低版本paper可以正常运作
![image](https://user-images.githubusercontent.com/103288982/167893970-fa3b52a2-d3d3-4418-87cd-d9d74b678afe.png)


### 🗄 Server log

[Server thread/INFO]: [TrMenu] Loading TrMenu v3.1.10
[12:00:37] [Server thread/INFO]: [m[m
[12:00:37] [Server thread/INFO]: [0;37;22m正在加载 [0;36;22mTr[0;36;1mMenu [0;37;1m[21mPremium... [0;30;1mgit-PaperSpigot-445 (MC: 1.8.8)[m
[12:00:37] [Server thread/INFO]: [m[m


```

### ⚙ Configurations

```

```

**Comment by 157946a** [comment]
发报错，而不是发pl
