### ISSUE TITLE
[问题]: 插件未能正常启用

### ISSUE THREAD

**Issue by MCJiaoLong** [InsinuateProjects/TrMenu#186]
### 🚀 是否已尝试最新的版本

- [x] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

无

### 🔍 详细的描述

服务器版本: 1.13.2-R0.1-SNAPSHOT
插件版本: TrMenu-3.1.10 (当天最新构建)

服务器插件列表:
![Server Plugins-1](https://user-images.githubusercontent.com/75253383/169641035-00496c34-516f-4cd5-be3c-6cf2fc7e97a3.png)

### 🗄 服务端日志

![Error Report-2](https://user-images.githubusercontent.com/75253383/169640944-25e77fd7-483f-417a-84a6-f0e92d031cb8.png)

### ⚙ 配置文件

无

**Comment by konsheng** [comment]
![This is an image](https://2891838427-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F8rYkctFKWbx7j44p8epf%2Fuploads%2FiFbhl20uZz4MvNHPEHby%2F%E5%9B%BE%E6%80%AA%E5%85%BD_ff5f7af88d460afd2913d6122ac98642_72706.png?alt=media&token=855abeaf-3af3-4946-8f24-b8d8f1485d95)
