### ISSUE TITLE
无法使用CMI的经济系统

### ISSUE THREAD

**Issue by GXLiLuoQin** [InsinuateProjects/TrMenu#19]
建议内置兼容CMILib的经济模块

**Comment by 157946a** [comment]
你是不是用了cmi作者的vault版本

**Comment by GXLiLuoQin** [comment]
因为最初没有安装vault导致的误判，抱歉给您带来困扰



在 2021-09-08 17:53:04，"157946a" ***@***.***> 写道：

你是不是用了cmi作者的vault版本

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 157946a** [comment]
如果你方便的话,可以试着用cmi作者界面的vault测试看看能不能正常使用cmi经济系统,如果能,就是没有什么问题的

**Comment by GXLiLuoQin** [comment]
在使用，目前没什么问题，但还是请尽快修复打开其他插件GUI界面时不被判定为关闭菜单操作的问题

**Comment by 157946a** [comment]
后者这个你更新看看,我记得修了的

**Comment by GXLiLuoQin** [comment]
对对，我刚刚没看那个回复，所以误发
