### ISSUE TITLE
[Bug]: js條件錯誤

### ISSUE THREAD

**Issue by MusicTW** [InsinuateProjects/TrMenu#191]
### 🚀 Have you tried the latest version

- [X] I have updated TrMenu to the latest version and the same bug is reproduced.

### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

輸出有問題，無法列出網址
https://pastebin.com/N81RM45j

### 🔍 Detailed description

js條件式無法正常列出結果，會判斷錯誤，是結果顯示錯誤，並不會後台報錯
條件數字>=1000貌似也無法正常判斷
https://pastebin.com/FWjqLci9

### 🗄 Server log

```

```

### ⚙ Configurations

```

```

**Comment by MusicTW** [comment]
https://pastebin.com/YXEBBwWQ
我改這樣寫就正確了

**Comment by 157946a** [comment]
数值的双引号删除即可
