### ISSUE TITLE
I've tried the latest build, and it seems the issues wasn't actually been fixed

### ISSUE THREAD

**Issue by RE4ERKA** [InsinuateProjects/TrMenu#2]
[latest.log](https://github.com/InsinuateProjects/TrMenu/files/6943414/latest.log)

**Comment by Score2** [comment]
Because the format in the language file has changed a lot, you need to delete the original language file, and then restart your server so that they can generate the correct language file again.

**Comment by RE4ERKA** [comment]
Sorry for bothering you, but still, problem with command "/trmenu open example nickname" did not work.

I join to server, and I'm still writing that I'm not online.

![image](https://user-images.githubusercontent.com/66727581/128483316-2f3b91f8-3814-4390-b1f2-d21e8cca29e8.png)

**Comment by Score2** [comment]
Fixed
