### ISSUE TITLE
openj9无法使用,启动完成后Trmenu自动卸载了

### ISSUE THREAD

**Issue by 3154311518** [InsinuateProjects/TrMenu#224]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

操作系统: Windows10
Java版本: ibm openj9 jdk11
服务端: PaperSpigot-445 (MC: 1.8.8)
Trmenu版本: 3.1.16

### 🔍 详细的描述

openj9无法使用,启动完成后Trmenu自动卸载了

### 🗄 服务端日志

[latest.log](https://github.com/InsinuateProjects/TrMenu/files/9698795/latest.log)

### ⚙ 配置文件

```

```

**Comment by XiaoJie-150** [comment]
使用8或者11
