### ISSUE TITLE
处理这样%playerlist_online,normal,yes,2%的变量似乎有问题

### ISSUE THREAD

**Issue by HySand** [InsinuateProjects/TrMenu#23]
%playerlist_online,normal,yes,num% 返回的应该是玩家名或Offline
好像无法正确检查和表达变量
`head:%playerlist_online,normal,yes,0%` 不能正常显示头颅
`check papi *%playerlist_online,normal,yes,1% == *Offline`不能正常检查papi
似乎只检查到online,后面的部分都没了

`[10:56:09 INFO]: [TrMenu] Timeout while parsing kether shell:`
`[10:56:10 INFO]: [TrMenu] Timeout while parsing kether shell:`
`[10:56:10 INFO]: [TrMenu] Timeout while parsing kether shell:`
`[10:56:10 INFO]: [TrMenu] Timeout while parsing kether shell:`
`[10:56:10 INFO]: [TrMenu] Timeout while parsing kether shell:`
`[10:56:11 INFO]: [TrMenu] Timeout while parsing kether shell:`
`[10:56:11 INFO]: [TrMenu] Timeout while parsing kether shell:`
`[10:56:11 INFO]: [TrMenu] Timeout while parsing kether shell:`
`[10:56:11 INFO]: [TrMenu] Timeout while parsing kether shell:`

不知道是我配置错了还是BUG

附上测试用的菜单 yml
[test.zip](https://github.com/InsinuateProjects/TrMenu/files/6972555/test.zip)

**Comment by Score2** [comment]
Kether目前仍然在修复，建议使用js来代替kether。只要在condition条件最前面加上个js:
就能使用js条件

**Comment by HySand** [comment]
头颅也是这个问题吗
有这个报错，但只有第一次有
`[10:27:53 INFO]: [Texture] Texture player %playerlist_online not found.`
整不明白了

**Comment by Score2** [comment]
尝试 `%playerlist_online\,normal\,yes\,1%`

**Comment by HySand** [comment]
这样似乎都获取不到参数了，返回了playerlist变量的使用方法。
此外我还尝试了
`Functions:
  p0:
    get: vars("head:%playerlist_online,normal,yes,0%")`
结果物品变成缰绳了...
material: '${p0.get}'

**Comment by wzq20010724** [comment]
> 这样似乎都获取不到参数了，返回了playerlist变量的使用方法。
> 此外我还尝试了
> `Functions:`
> ` p0:`
> ` get: vars("head:%playerlist_online,normal,yes,0%")`
> `material: '${p0.get}'`
> 和
> `Functions:`
> ` p0:`
> ` get: vars("%playerlist_online,normal,yes,0%")`
> `material: 'head:${p0.get}'`
> 结果物品变成缰绳了...

尝试使用
```
      material: 'source:JS:
      function test() {
        var head = new ItemStack(Material.PLAYER_HEAD);
        var meta = head.getItemMeta();
        meta.setOwner(vars("%playerlist_online,normal,yes,0%"));
        head.setItemMeta(meta);
        return head;
      }
      test();
      '
```
暂时凑合一下

**Comment by Score2** [comment]
已修复，请关注最新的构建。
