### ISSUE TITLE
[功能]: Please update to 1.19.4

### ISSUE THREAD

**Issue by CCjun6** [InsinuateProjects/TrMenu#233]
### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 🔍 详细的描述

This plugin doesn't work in version 1.19.4 please update thanks

### ⚙ 配置文件

```

```

**Comment by CCjun6** [comment]
Please update as soon as possible after seeing it
I am willing to provide sponsorship if necessary
Please leave a sponsorship channel

**Comment by polang233** [comment]
我也觉得1.19.4可以更新下，就当是trmenu最后版本吧...
