### ISSUE TITLE
 Plugin does not work on paperspigot 1.8.8

### ISSUE THREAD

**Issue by RE4ERKA** [InsinuateProjects/TrMenu#27]
Core: paper-1.8.8-443
Plugins: TrMenu-3.0-PRE-15, PlaceholderAPI-2.10.10

Logs:
[latest.log](https://github.com/InsinuateProjects/TrMenu/files/6986602/latest.log)

**Comment by Score2** [comment]
https://github.com/InsinuateProjects/TrMenu/wiki/migrate

**Comment by Score2** [comment]
It is not recommended that you run TrMenu on 1.8 server.
1.8 server we have not done adaptation.
Only TrMenu-pre9 is the best support.:)

**Comment by RE4ERKA** [comment]
Thank you! The plugin is working.

**Comment by RE4ERKA** [comment]
Many things do not work correctly in trmenu-pre9, will support for 1.8 be added and how soon in the latest version of trmenu?
