### ISSUE TITLE
JS替换语句变量变更后无法重新判断

### ISSUE THREAD

**Issue by Super-10** [InsinuateProjects/TrMenu#28]
只能重载菜单来重新获取变量
已经领取过了，但Lore因为变量的
判断仍然没有更改
而条件语句用JS判断变量是可以的
![image](https://user-images.githubusercontent.com/65401527/129468349-1488905e-a062-4e74-a1b3-204b6abcc1a6.png)
![image](https://user-images.githubusercontent.com/65401527/129468418-79d610f7-2293-46ab-96ad-0e1288b20d4c.png)

**Comment by Neige7** [comment]
答案是使用update定时更新按钮
