### ISSUE TITLE
使用update后物品数量只有一个

### ISSUE THREAD

**Issue by Super-10** [InsinuateProjects/TrMenu#29]
![image](https://user-images.githubusercontent.com/65401527/129468839-3df0e838-3509-4046-977d-c828c8d07b8f.png)
![image](https://user-images.githubusercontent.com/65401527/129468845-2d0f37fd-0136-4164-99fa-a28bceb08f9f.png)

**Comment by Score2** [comment]
请尝试最新的构建验证该问题是否解决:)

如果仍存在问题，请使用`/trm debug dump` 补充服务端信息.

**Comment by Score2** [comment]
尝试使用pre23
