### ISSUE TITLE
副手切換鍵問題

### ISSUE THREAD

**Issue by MusicTW** [InsinuateProjects/TrMenu#30]
TrMenu版本：3.0PRE-15
伺服器版本：paper783 + java16
第一次開啟並關閉選單之後會無法使用副手切換鍵
需重新開啟一次選單問題才會解決
問題展示影片
https://imgur.com/a/ltbdR0M

**Comment by MusicTW** [comment]
https://paste.helpch.at/zeviteyudu
上次沒有做trmenu debug dump
這次補用
雖然是PRE19版
但問題仍有發生

**Comment by MusicTW** [comment]
過了16天，版本有持續更新，但bug尚未修復

**Comment by Score2** [comment]
很抱歉，最近我在上学，近来几个更新仅仅为taboolib更新以及一些小问题的修复。我会在放假后尽快将该问题排上日程:)

**Comment by 157946a** [comment]
尝试使用最新版,看看是否修复了,如果未修复,请下载这个软件重新录一个视频,把这个软件也录进去,我们好观看到你键盘上的操作https://cowtransfer.com/s/6d691efe40eb45

**Comment by MusicTW** [comment]
目前測試沒有問題，感謝Orz
