### ISSUE TITLE
右键绑定物品打开一次后，第二次无法打开菜单（1.17.1）

### ISSUE THREAD

**Issue by GXLiLuoQin** [InsinuateProjects/TrMenu#31]
如题，这是个BUG

**Comment by Score2** [comment]
是否有出现报错信息.

**Comment by GXLiLuoQin** [comment]
没有



在 2021-08-15 21:53:59，"Score2" ***@***.***> 写道：

是否有出现报错信息.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 157946a** [comment]
你是怎么操作,导致的打开一次物品后无法打开第二次

**Comment by GXLiLuoQin** [comment]
因为打开了其他插件的GUI界面，无报错信息，抱歉回复过晚，由于我正在大学校园



在 2021-09-08 19:21:34，"157946a" ***@***.***> 写道：

你是怎么操作,导致的打开一次物品后无法打开第二次

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 157946a** [comment]
理解理解,如果是因为打开其他gui导致的无法再次打开的话,你使用最新版本,把close去掉,从trmenu打开别的插件gui,看看是否还会出现无法再次打开

**Comment by GXLiLuoQin** [comment]
感谢

**Comment by GXLiLuoQin** [comment]
我也感觉是因为这些非正常关闭的问题，但得到了解决还是很满足了
