### ISSUE TITLE
无法显示 color hex 色码

### ISSUE THREAD

**Issue by winnyok2042** [InsinuateProjects/TrMenu#34]
无法显示 color hex 色码

| Server : paper-1.16.5-786
| Java version: 16

Installed Plugins: 
· PlaceholderAPI - 2.10.9
· TrMenu - 3.0-PRE-16

**Comment by Score2** [comment]
请提供用于复现HexColor问题的菜单

**Comment by winnyok2042** [comment]
> 你是如何使用的？
> 请提供用于复现HexColor问题的菜单

跟以前v2.08一样的使用方法

    display:
      name: ' §f【§r<#9b54f7>test §f】'
      lore:
        - '§a『<#32A852>test §a』'
      material: NETHERITE_CHESTPLATE

**Comment by Neige7** [comment]
> > 你是如何使用的？
> > 请提供用于复现HexColor问题的菜单
> 
> 跟以前v2.08一样的使用方法
> 
> ```
> display:
>   name: ' §f【§r<#9b54f7>test §f】'
>   lore:
>     - '§a『<#32A852>test §a』'
>   material: NETHERITE_CHESTPLATE
> ```

严重的错误使用，请使用&{#000000}格式尝试
