### ISSUE TITLE
Can't join Server

### ISSUE THREAD

**Issue by Galaxy-VN** [InsinuateProjects/TrMenu#35]
I can't join server on a latest version trmenu

1. Install trmenu

**Screenshots**
![image](https://user-images.githubusercontent.com/52485153/129739537-6aac94c6-6313-4fd5-a31e-033f2f4bb7c3.png)

**Server Information**
Can't event dump it
Its genrate out this: https://paste.helpch.at/vesiyohici.md

TrMenu Dump Information (Date: xxxx-xx-xx xx:xx:xx)

| Server OS: Windows Server 2016 amd64 10.0
| Server software: git-Purpur-1171 (MC: 1.16.5) (1.16.5-R0.1-SNAPSHOT)
| Java version: 16.0.1

| TabooLib: 6.x
| TrMenu: 3.0-PRE-18
Installed Plugins: 
· PlaceholderAPI - 2.10.10
· TrMenu - 3.0-PRE-18
```

**Comment by Score2** [comment]
建议暂时回退版本到 pre16，该问题待修复.:)

**Comment by Galaxy-VN** [comment]
> 建议暂时回退版本到 pre16，该问题待修复.:)

我不知道怎麼做，但是當我使用 pre16 和 relogin 時，它們一直在崩潰

**Comment by Score2** [comment]
Sorry, I just woke up and accidentally used Chinese to talk to you.😥
You can temporarily roll back to a version that has no errors before, and we will fix this issue as soon as possible.:)

**Comment by 157946a** [comment]
Just reduce TrMenu to the second build. The first build contains new bugs. I have tested it.

**Comment by Galaxy-VN** [comment]
> Sorry, I just woke up and accidentally used Chinese to talk to you.😥
> You can temporarily roll back to a version that has no errors before, and we will fix this issue as soon as possible.:)

sure i will wait for it thanks

**Comment by Score2** [comment]
Try to use latest build.:)

**Comment by Galaxy-VN** [comment]
> Try to use latest build.:)

its worked ty <3
