### ISSUE TITLE
Kether无法识别papi占位符

### ISSUE THREAD

**Issue by qianchen36** [InsinuateProjects/TrMenu#36]
在Kether中使用了papi占位符
`- condition: '%trmenu_data_time% != %thetime_date_week%'`
`- condition: '%trmenu_data_own-1% >= 10'`
Console报错papi的占位符为Unknown Action
(报错中直接展示了papi占位符，而不是应当替换成为的数据)
然后只执行condition的deny分支

**Comment by Score2** [comment]
建议多看看wiki。
https://kether.tabooproject.org/standard#check
TrMenu默认条件使用的是 kether，而你使用的语法是属于 js 的
如果要使用 js 语法, 那就在 condition 前面加上 `js: `
