### ISSUE TITLE
Gradient 

### ISSUE THREAD

**Issue by DraimCiDo** [InsinuateProjects/TrMenu#39]
Is gradient implemented in v3 version?

> In old version: `{g:#RRGGBB:#RRGGBB}`
> But in new version that don`t work.

At the moment, i found out HexCode works through FunctionParser.kt
![image](https://user-images.githubusercontent.com/53317146/129891551-d395aff3-73a7-4f18-bf11-de9c94d45e06.png)

As you can see, it can use gradient, as i indicated above 
27 line - `{ "${it[1]}:${it[2]}" }`
but unfortunately gradient code is not spelled out, therefore, it most likely does not work.
If this is case, could you add this feature?

this functionality was already in [v2.0](https://github.com/TrMenu/TrMenu/blob/b141e0d0d72f940a1eeae10e052a6a3cec6f590d/src/main/kotlin/me/arasple/mc/trmenu/util/Hex.kt)
![image](https://user-images.githubusercontent.com/53317146/129892414-dc3be8a1-fbe9-4da5-86f0-f28396bafdf3.png)

**Comment by Score2** [comment]
Please look forward to TrMenu-PRE20:)
format: <g:#yourMinHex:yourMaxHex>This is gradient  text<g:#yourMinHex:yourMaxHex:l>

**Comment by Score2** [comment]
Fixed in latest build.:)
