### ISSUE TITLE
捕获器类型ANVIL,BOOK无法使用

### ISSUE THREAD

**Issue by Spihea** [InsinuateProjects/TrMenu#42]
版本:PaperSpigot1.8.9
JAVA:JAVA8 281
使用捕获器时BOOK与ANVIL无法使用且报错
![QQ图片20210819171627](https://user-images.githubusercontent.com/60551450/130043555-90d4018d-7dc8-4884-90fd-80e4639aacb0.png)
![QQ图片20210819171943](https://user-images.githubusercontent.com/60551450/130043589-8e05fc4f-7060-4821-b0d6-70c64a07a0e7.png)
[!] 图1为BOOK 图2为ANVIL

**Comment by Score2** [comment]
书本捕获仍然需要测试来验证是否修复，如果有错误请提供新的报错.
