### ISSUE TITLE
指令无法被补全但能使用

### ISSUE THREAD

**Issue by Super-10** [InsinuateProjects/TrMenu#45]
**Describe the bug**
指令被注册后无法被Tab补全并且在游戏中会为红色

**To Reproduce**
1. settings.yml里注册指令
2. 输入指令

**Expected behavior**
能被Tab补全并且正常注册指令

**Screenshots**
![image](https://user-images.githubusercontent.com/65401527/130198071-55797dec-b410-4871-a13d-d47904ecbcdc.png)
![image](https://user-images.githubusercontent.com/65401527/130198531-dc92edc5-0aaa-4f09-a202-cec17b09fe04.png)

**Additional context**

**Server Information**
> Use command `/trm debug dump` to get the information
> Copy the information to below
e.g.
```
TrMenu Dump Information (Date: xxxx-xx-xx xx:xx:xx)

| Server OS: Windows 10
| Server software: yatopia-1.16.5-paperclip-b122
| Java version: JDK16

| TabooLib: 6.x
| TrMenu: 3.0-PRE-19
Installed Plugins: 
· LuckPerms-Bukkit-5.3.51
· PlaceholderAPI-2.10.10
· TrMenu - 3.0-PRE-19
```

**Comment by Score2** [comment]
补全需要重启服务端才生效

**Comment by Super-10** [comment]
> 补全需要重启服务端才生效

重启过了

**Comment by Super-10** [comment]
> 补全需要重启服务端才生效
我用Yatopia 1.16.5的核心新开了个服务端只装TrMenu和PlaceholderAPI照样无法补全指令

**Comment by Super-10** [comment]
> 补全需要重启服务端才生效

我用Yatopia 1.16.5的核心新开了个服务端只装TrMenu和PlaceholderAPI照样无法补全指令

**Comment by Score2** [comment]
1.12以下暂无此问题，待修复

**Comment by Super-10** [comment]
> 1.12以下暂无此问题，待修复

之前禁忌库已经修复过能用了 但是不知道为什么现在又成这样了

**Comment by qianchen36** [comment]
似乎带大写就不能不全，全小写可以

**Comment by Score2** [comment]
尝试使用最新的构建:)
