### ISSUE TITLE
打开菜单报错

### ISSUE THREAD

**Issue by GoaTham** [InsinuateProjects/TrMenu#46]
使用/trmenu open 打开任何菜单都会刷这段报错，菜单也没有打开

https://paste.ubuntu.com/p/TcnpKkPTtC/

| TabooLib: 6.x
| TrMenu: 3.0-PRE-19
ServerCore: CatServer-26208f0-universal.jar

**Comment by Score2** [comment]
CatServer暂不支持

**Comment by Score2** [comment]
#12

**Comment by GoaTham** [comment]
I see. Thank you
