### ISSUE TITLE
BC端不能获取头像

### ISSUE THREAD

**Issue by Zz-886** [InsinuateProjects/TrMenu#48]
**Describe the bug**
BC服无法显示玩家头像
**To Reproduce**
1. 连接BC端 waterfall-1.17-448 后进服不能正确获取头像。
2. 然后关服备份Paper-786服务器文件夹
3. 删除备份Paper-786服务器文件夹内和BC端有关的的设置文件以及SkinsRestorer文件夹
4. 开服后修改server.properties文件关闭正版验证
5. 再次开服测试能正常获取头像

**Expected behavior**
https://minecraft-heads.com/中的头可以显示，玩家的头像不能正常显示
**Screenshots**

**Additional context**

**Server Information**
> Use command `/trm debug dump` to get the information
> Copy the information to below
https://paste.helpch.at/uvurotemos
```
| Server OS: Windows 10 amd64 10.0
| Server software: git-Paper-786 (MC: 1.16.5) (1.16.5-R0.1-SNAPSHOT) + waterfall-1.17-448
| Java version: 16.0.2

| TabooLib: 6.0.0-PRE
| TrMenu: 3.0-PRE-20
Installed Plugins: 
· ActionHealth - 3.5.5 (0 KB)
· CMI - 9.0.2.7 (0 KB)
· CMIEInjector - 1.0.2.3 (0 KB)
· CMILib - 1.0.3.5 (0 KB)
· ChatManager - 3.7.4 (0 KB)
· CrazyAuctionsPlus - 1.1.9 (0 KB)
· EternalTags - 1.0.10 (0 KB)
· InteractionVisualizer - 1.16.3.9 (0 KB)
· LuckPerms - 5.3.61 (0 KB)
· MPoints - 1.2.2 (0 KB)
· Multiverse-Core - 4.3.1-SNAPSHOT-b857 (0 KB)
· PlaceholderAPI - 2.10.10 (0 KB)
· PlugMan - 2.2.5 (0 KB)
· ProtocolLib - 4.7.0 (0 KB)
· Residence - 5.0.0.2 (0 KB)
· SkinsRestorer - 14.1.3 (0 KB)
· TAB - 2.9.2 (0 KB)
· TrMenu - 3.0-PRE-20 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· mcMMO - 2.1.201 (0 KB)

**Comment by 157946a** [comment]
你是使用bc服吗,是不是打开了bungeecord的开关了,请先检查下

**Comment by Zz-886** [comment]
是的

**Comment by 157946a** [comment]
如果是打开了bc模式,请检查下子服的skin是否只有一个不属于yml后缀名的文件,如果是,就不需要在子服加skin,直接放bc的plugins即可

**Comment by Zz-886** [comment]
那我删掉子服的试下SkinsRestorer测试下

**Comment by Zz-886** [comment]
删除掉子服的SkinsRestorer可以获取到头像了，感谢 @157946a
