### ISSUE TITLE
无法使用指令

### ISSUE THREAD

**Issue by Baikele** [InsinuateProjects/TrMenu#53]
**Describe the bug**
无法使用/trmenu item toJson
json图标无法定时刷新

**To Reproduce**
可以实时刷新图标

**Expected behavior**

**Screenshots**

**Additional context**

**Server Information**
> Use command `/trm debug dump` to get the information
> Copy the information to below
e.g.
```
TrMenu Dump Information (Date: xxxx-xx-xx xx:xx:xx)

| Server OS: xxxx
| Server software: xxxx
| Java version: xxxx

| TabooLib: 6.x
| TrMenu: 3.0-PRE-20
Installed Plugins: 
· LuckPerms - 5.1.93
· PlaceholderAPI - 2.10.9
· TrMenu - 3.0-PRE-20
```

**Comment by Score2** [comment]
Try to use pre22.
Refresh only when the json icon contains variables.:)

**Comment by Score2** [comment]
`/trm debug dump`

**Comment by 157946a** [comment]
有没有更多的信息,比如在宝可梦这种服务器里,用变量显示槽位的精灵等等,使用最新版再次测试看看有没有这种情况
