### ISSUE TITLE
输入命令/trmenu后出现的提示文字不合理

### ISSUE THREAD

**Issue by JinOuYongGu** [InsinuateProjects/TrMenu#56]
**Describe the bug**
![image](https://user-images.githubusercontent.com/45219386/131318241-a63fbb8c-b304-461e-bcf6-774cbd883127.png)

**To Reproduce**
1.输入命令/trmenu即可

**Expected behavior**
文字描述与命令关键字相匹配

**Screenshots**
![~ITY% FWC}2UJ30A`P78O_K](https://user-images.githubusercontent.com/45219386/131318320-9fb4f74b-7efe-4d90-91ff-468845ad3288.png)

**Additional context**
暂无

**Server Information**
任意环境均可复现

**Comment by 157946a** [comment]
这个我已经和作者反馈过了,你也可以选择关闭

**Comment by JinOuYongGu** [comment]
好的 那我就close了
