### ISSUE TITLE
使用除SIGN外的其他三种捕获器,执行'console:'行为会报错

### ISSUE THREAD

**Issue by Lemonadesuda** [InsinuateProjects/TrMenu#57]
**Describe the bug**
在使用Catcher时我发现当使用chat、anvil、book时，如果下面的actions用的是'console'会出现报错（目前已知只有这个）

**To Reproduce**
配置文件:
[https://pastebin.com/Hiicbiaf](url)
（条件判断为持有经济是否大于输入值）
可以发现除了用SIGN作为Catcher，其他捕获器都出现了报错

**Expected behavior**
输入后执行action内的行为

**Screenshots**
问题如图:
![GIF 2021-8-31 10-47-52](https://user-images.githubusercontent.com/89823814/131436320-840fa4c0-8bf5-48c7-8b91-ece8a58e1064.gif)
报错记录:
[https://pastebin.com/hx3wKxZh](url)

**Additional context**
目前经过简短测试，似乎只有console不可以使用

TrMenu Dump Information (Date: xxxx-xx-xx xx:xx:xx)
https://paste.helpch.at/eqoqibogab

**Comment by Score2** [comment]
命令能够正常执行，可以暂时忽略它. 将在下个版本修复报错.

**Comment by Lemonadesuda** [comment]
谢谢大大了
