### ISSUE TITLE
set-data 无法储存数据

### ISSUE THREAD

**Issue by liaojinmin** [InsinuateProjects/TrMenu#65]
如题，经过多次测试，设置data数据后，一旦关服或重启，数据统统消失，将近一半菜单暂无法使用，望修复。

| Server OS: win10
| Server software: 1.16.5
| Java version: 11

| TabooLib: 6.x
| TrMenu: 3.0-PRE-23

**Comment by 157946a** [comment]
复现,等维护者修复
