### ISSUE TITLE
一个非常严重的问题 请立即修复 

### ISSUE THREAD

**Issue by yuankun1** [InsinuateProjects/TrMenu#66]
trmenuv3 23
paper 1.17.1
一个区块同时存在很多实体 会导致玩家客服端延迟
 也用排除法 单独加一个trmenuv3 23 我已经做过了测试
但是服务器 TPS不影响

**Comment by Score2** [comment]
客户端出现延迟时的带宽占用状况如何

**Comment by yuankun1** [comment]
> 客户端出现延迟时的带宽占用状况如何

都是正常的 服务器也是正常的 客服端也是正常的
我一直以为是我网络问题 直到我单独测试 才发现的
我只测速了外网vps 内网没测速过

**Comment by 157946a** [comment]
机器配置应该很好吧,可以发出来吗

**Comment by yuankun1** [comment]
> 机器配置应该很好吧,可以发出来吗

8222lCPU 之前i9 10900k 一样的
我移除trmenu 就不会出现以上的问题
之前CMI 的传送门粒子效果 也会延迟玩家  也是不影响服务器 不知道跟你的trmenu是不是同一个原理
但是CMI 的作者已经修复了

**Comment by Bkm016** [comment]
什么东西你就挂我

**Comment by Bkm016** [comment]
查到啥问题了吗

**Comment by 157946a** [comment]
你配置中是否有title-update,删除看看是否还会卡顿

**Comment by yuankun1** [comment]
> 你配置中是否有title-update,删除看看是否还会卡顿,同时输入指令trmenu debug dump生成的链接放上来,卡的时候生成timings也放上来

貌似只有靠近生物比较多的区块 就会导致玩家延迟 开便不会 

配置文件是默认生成的
https://timings.aikar.co/?id=0bcf1b49a3b84a75b071cfca07a8ccb1
https://paste.helpch.at/equjumetep.
只有玩家客服端会延迟 后台不影响

**Comment by 157946a** [comment]
生物较多时卡顿的话,今天早上测了一下,超过13-14个左右就开始严重卡顿了,你手动放生物看看

**Comment by yuankun1** [comment]
> 生物较多时卡顿的话,今天早上测了一下,我手动放生物超过13-14个左右就开始严重卡顿了,你手动放生物看看

我就是手动放生物的 超过42个生物就开始卡延迟玩家客服端了

**Comment by 157946a** [comment]
42个,不错了吧,我tr三件套十几个就卡了,而且平常应该也不会一次性有那么多怪物的吧..........

**Comment by yuankun1** [comment]
我突然发现trchat也是一样原理我怀疑是不是怀黑的TabooLib 的问题

**Comment by 157946a** [comment]
你再分别测试下,trhd,adyeshach,单独测试看看

**Comment by yuankun1** [comment]
> 你再分别测试下,trhd,adyeshach,单独测试看看

你说的这两个没有1.17的版本或者是修复版我测试不了

**Comment by yuankun1** [comment]
我也希望这个问题能尽快解决因为 如果不尽快我可能就要替换 trchat 跟trmenu的
我认为这两个是不错的插件

**Comment by 157946a** [comment]
> > 你再分别测试下,trhd,adyeshach,单独测试看看
> 
> 你说的这两个没有1.17的版本或者是修复版我测试不了

你错了,这两都有了,trhd是mical接手了,并且已经兼容了,我测试过了的,adyeshach既是坏黑的插件,也兼容了,最新版的

**Comment by yuankun1** [comment]
> > > 你再分别测试下,trhd,adyeshach,单独测试看看
> > 
> > 
> > 你说的这两个没有1.17的版本或者是修复版我测试不了
> 
> 你错了,这两都有了,trhd是mical接手了,并且已经兼容了,我测试过了的,adyeshach既是坏黑的插件,也兼容了,最新版的

麻烦能发个连接吗我测试一下

**Comment by 157946a** [comment]
trhd: https://www.mcbbs.net/thread-1247555-1-1.html
adyeshach: https://www.mcbbs.net/thread-1121230-1-1.html

**Comment by Score2** [comment]
> > > > 你再分别测试下,trhd,adyeshach,单独测试看看
> > > 
> > > 
> > > 你说的这两个没有1.17的版本或者是修复版我测试不了
> > 
> > 
> > 你错了,这两都有了,trhd是mical接手了,并且已经兼容了,我测试过了的,adyeshach既是坏黑的插件,也兼容了,最新版的
> 
> 麻烦能发个连接吗我测试一下

在它们开源地址下的actions里均可下载到最新的构建

**Comment by yuankun1** [comment]
OK了 我测试过了
trhd 相比没怎么严重 但是会有一定影响
adyeshach 比其他严重很多

**Comment by 157946a** [comment]
@Bkm016
