### ISSUE TITLE
Paper1.17.1使用卡顿

### ISSUE THREAD

**Issue by User926** [InsinuateProjects/TrMenu#67]
| Server OS: Windows 2019 64
| Server software: TrMenu-3.0-PRE-15 - 21
| Java version:  Java16.0.1

| TabooLib: 6.x
| TrMenu: 3.0-PRE-20

安装  TrMenu-3.0-PRE-15 - 21 在服务器中会导致延迟飙升，本地链接也一样，特别是实体比较多的时候。

**Comment by Score2** [comment]
#66
