### ISSUE TITLE
功能失效

### ISSUE THREAD

**Issue by QQ464944870** [InsinuateProjects/TrMenu#68]
Config文件中可以看到这个设置
大概是绑定物品打开菜单的时间间隔
我改成1和100000都是一样的
应该节点失效了
Menu:
  Settings:
    Bound-Item-Interval: 100000

**Comment by Score2** [comment]
```
/trm debug dump
```

**Comment by 157946a** [comment]
问题不大,不是配置不生效,是trmenu reload不会重载settings的内容,导致不生效
