### ISSUE TITLE
普通玩家使用RegisterCommands注册的命令提示无权限

### ISSUE THREAD

**Issue by minemryf** [InsinuateProjects/TrMenu#69]
**Describe the bug**
任何普通玩家执行RegisterCommands注册的命令都会提示无权限.

**Expected behavior**
它应该正常运作.

**Screenshots**
![image](https://user-images.githubusercontent.com/72493700/133026709-1ba5fdea-3548-4aeb-b30f-00948bb5b0da.png)
![image](https://user-images.githubusercontent.com/72493700/133026745-571da1c7-a4a7-4861-bba2-4ed43b710bef.png)

**Additional context**
我将服务器中不相关的插件全部卸载，仅剩下AuthMe-5.6.0-beta2、LuckPerms-Bukkit-5.3.47、ProtocolLib、TrMenu-3.0-PRE-24时，并且所有注册的命令需求权限都为null，即使如此依然无权限执行任何命令.

**Server Information**
> Use command `/trm debug dump` to get the information
> Copy the information to below
e.g.
```
无

| Server OS: windows server 2019
| Server software: Paper 1.12.2
| Java version: Java11

| TabooLib: 6.x
| TrMenu: 3.0-PRE-16
Installed Plugins: 
· AuthMe-5.6.0-beta2
· LuckPerms-Bukkit-5.3.47
· ProtocolLib
· TrMenu-3.0-PRE-24
```

**Comment by minemryf** [comment]
我给它写一个test权限并给予玩家后可以正常使用，只有在为null的状态下是不可用的，即使给了null这个权限也不行
![image](https://user-images.githubusercontent.com/72493700/133027651-b322da9a-36d9-495e-bd6e-1c381508ed21.png)
![image](https://user-images.githubusercontent.com/72493700/133027667-b82d2e01-cff6-446e-9b2b-77c9a484ac8f.png)

**Comment by Score2** [comment]
尝试 `permission: ''`

**Comment by 157946a** [comment]
你先更新插件,看看是否还有这个问题
