### ISSUE TITLE
头颅皮肤不显示

### ISSUE THREAD

**Issue by qaz197418i** [InsinuateProjects/TrMenu#7]
各种头颅的获取方式，包括hdb都不起作用，都被显示为了苦力怕的头
![image](https://user-images.githubusercontent.com/30312760/128623506-7a011a78-82cc-4cfe-b3dd-c24e75f48036.png)
![image](https://user-images.githubusercontent.com/30312760/128623513-6a9c82e8-dd3b-48bc-8e53-84857c6d14c1.png)

**Comment by Score2** [comment]
请提供 TrMenu 版本

**Comment by qaz197418i** [comment]
> 请提供 TrMenu 版本
> 以及 Minecraft 版本

使用的是当前最新版本的TrMenu
服务器版本为paper 1.12.2

**Comment by Score2** [comment]
等待 TabooLib 6.0.0-pre33 的推送以修复.

**Comment by Score2** [comment]
Fixed in pre14
