### ISSUE TITLE
Problem loading libraries

### ISSUE THREAD

**Issue by EliasDavid256** [InsinuateProjects/TrMenu#72]
Basically, when loading TrMenu libraries, the server simply does not load or takes too long to load. Even, sometimes I have to try to start up to 4 times, so that the server finally loads.

Java: Version 16, OpenJDK.
Version: 1.17.1.
S.O: Linux.

I use the Pterodactyl Software panel, together with Aikar flags.

It happens to me on all servers, where I use TrMenu.

**Comment by 157946a** [comment]
Enter the command trmenu debug dump, and then send the link up

**Comment by EliasDavid256** [comment]
I don't get any errors when starting (although sometimes I do).

However, I can even give you an access to my dashboard, so you can see.

The load does not usually go from here:

![image](https://user-images.githubusercontent.com/68405557/133460275-4d009178-37d6-408e-b416-2bdb6dc7b836.png)

It is not another plugin, because when removing TrMenu, it loads correctly.

And even the problem happens, having only TrMenu loaded.

**Comment by 157946a** [comment]
I did not see the error report of trmenu. Is trmenu installed? Please send the error report of trmenu

**Comment by EliasDavid256** [comment]
As I have described twice before; does not generate error.

But that "Loading Libraries, please wait ...", comes from TrMenu.

If I turn on a server only with TrMenu, it happens. If I remove TrMenu, it stops happening.

It stays in this space for hours and has to kill the server up to 3 times, so that it finally turns on.

**Comment by 157946a** [comment]
What are the plugins in plugins, send it up. Try to install PlaceholderAPI and TrMenu only

**Comment by 157946a** [comment]
Use the latest version to see if this is still the case

**Comment by 1636578433** [comment]
ovh新加坡的伺服器也會出現這樣的問題

**Comment by 1636578433** [comment]
不知道是不是網絡關係,有時候卡住可是有時候又加載得了

**Comment by 157946a** [comment]
Use latest build

**Comment by 157946a** [comment]
Use the latest build to see if the problem persists

**Comment by 1636578433** [comment]
![image](https://user-images.githubusercontent.com/26202461/172907436-68f06b58-58c6-4e7a-9cd9-4554cc778f54.png)
会卡在这里

**Comment by 1636578433** [comment]
我本机是可以直接访问的,只是面板服务器那边不可以

**Comment by 157946a** [comment]
> 我本机是可以直接访问的,只是面板服务器那边应该不可以

不要说应该，测试是否能过，如果面板服务器那边过不了的话，使用你自己的电脑生成后复制libs进你面板服务器重启

**Comment by EliasDavid256** [comment]
Fix!
