### ISSUE TITLE
IA物品名称没法正确地通过KetherX语句返回

### ISSUE THREAD

**Issue by Caishangqi** [InsinuateProjects/TrMenu#73]
**Describe the bug**
使用判断条件来返回物品名称更改菜单按钮 `material`时，IA物品名称无法被菜单识别(显示基岩),原版物品则可以正常使用

**To Reproduce**
1. 创建3个按钮，其中一个按钮的material用 KetherX输出原版物品材料，另一个输出IA物品材料名称，最后一个材料不用KetherX语句直接使用IA物品名称。
2. 可以看到IA物品名称通过KetherX返回时不被菜单识别为IA物品名称。

**Expected behavior**
使用KetherX时应该也能正常返回IA物品名称

**Screenshots**
三个对比的结果
![C} 0M G%LXY6`_17 V W36G](https://user-images.githubusercontent.com/39553613/133777422-1f3a1cd8-3b04-472e-aced-332a86eb5cfe.png)
再打开菜单时测试KetherX是否能正常返回IA物品值
![M6%NZG97X~K@PC~~_$J0)FK](https://user-images.githubusercontent.com/39553613/133777530-4c4fcc80-dfce-4ddb-bf74-f09ecf9e9e43.png)

**Additional context**
[菜单.yml](https://paste.ubuntu.com/p/6fcSbzNnRm/)

**Server Information**
> Use command `/trm debug dump` to get the information
> Copy the information to below
https://paste.helpch.at/ikufukoboq
```
TrMenu Dump Information (Date: xxxx-xx-xx xx:xx:xx)

| Server OS: Windows Server 2019 amd64 10.0
| Server software: git-Paper-259 (MC: 1.17.1) (1.17.1-R0.1-SNAPSHOT)
| Java version: 16.0.1

| TabooLib: 6.0.0-PRE
| TrMenu: 3.0-PRE-25
Installed Plugins: 
· LuckPerms - 5.3.57
· PlaceholderAPI - 2.10.10-DEV-132 
· TrMenu - 3.0-PRE-25
```

**Comment by 157946a** [comment]
你自己的格式问题,把then和else后面的都用{}圈起来即可,比如{set test to *source:IA:guis:slot_opaque}

**Comment by Caishangqi** [comment]
> 你自己的格式问题,把then和else后面的都用{}圈起来即可,比如{ set test to *source:IA:guis:slot_opaque }

不行，我看文档写的，没让加{}, 我刚刚也试了，加了`{ }` 也不管用

**Comment by 157946a** [comment]
他这个是判断然后返回内容,你可以在打开菜单事件这么写,用tr的参数功能,先判断,再在通过和不通过的下面写不同的参数,然后材质获取参数即可

**Comment by 157946a** [comment]
比如
- condition: 'money *2000'
  actions:
  - '设置参数1:source:IA:guis:slot_opaque'
  deny:
  - '设置参数1:source:IA:guis:button_locked'

是一样的效果

**Comment by Caishangqi** [comment]
> 比如
> 
> * condition: 'money *2000'
>   actions:
>   
>   * '设置参数1:source:IA:guis:slot_opaque'
>     deny:
>   * '设置参数1:source:IA:guis:button_locked'
> 
> 是一样的效果

是的，我一开始是用KetherX这么写的，但是我发现（可能是我在文档上没看到）参数好像是局部的没法传给`material:`里面，然后我就想试试在一行动作执行里面完成判断。

**Comment by 157946a** [comment]
是你没写对

**Comment by Caishangqi** [comment]
> 是你没写对,tr的动作是可用于整个菜单里的

谢谢，我再试试看。

**Comment by Caishangqi** [comment]
> 是你没写对,tr的动作是可用于整个菜单里的

我成功的可以传参，但是还是不能识别IA的物品类型 `source:IA:xxx:xxx`
这是[菜单的yml](https://paste.ubuntu.com/p/ZC97tHmJWg/)

**Comment by 157946a** [comment]
尝试将guis后面的冒号更改为别的符号看看,可能他把IA后的第二个冒号给判断成了和IA后第一个冒号一样的作用

**Comment by Caishangqi** [comment]
> 尝试将guis后面的冒号更改为别的符号看看,可能他把IA后的第二个冒号给判断成了和IA后第一个冒号一样的作用

不太行，我也尝试过使用custom model data给予变量值来对应不同的材质，但是像这么写`{model-data={data:glock1}}` 也不行

**Comment by 157946a** [comment]
等吧,到时候我和维护者看看

**Comment by Caishangqi** [comment]
> 等吧,到时候我和维护者看看

行，谢了。
![FPKJXO 1TH_CFQD7T(WMCIP](https://user-images.githubusercontent.com/39553613/133806784-67ce1660-ee3b-474f-9d7c-b4668daadd8a.png)

**Comment by paulreob** [comment]
> > 尝试将guis后面的冒号更改为别的符号看看,可能他把IA后的第二个冒号给判断成了和IA后第一个冒号一样的作用
> 
> 不太行，我也尝试过使用custom model data给予变量值来对应不同的材质，但是像这么写`{model-data={data:glock1}}` 也不行

The value of CustmomModelData is an integer
for example:
```
  'a':
    display:
      material: 'paper{model-data=8014}'

**Comment by 157946a** [comment]
> > > 尝试将guis后面的冒号更改为别的符号看看,可能他把IA后的第二个冒号给判断成了和IA后第一个冒号一样的作用
> > 
> > 
> > 不太行，我也尝试过使用custom model data给予变量值来对应不同的材质，但是像这么写`{model-data={data:glock1}}` 也不行
> 
> The value of CustmomModelData is an integer
> for example:
> 
> ```
>   'a':
>     display:
>       material: 'paper{model-data=8014}'
> ```

His problem is that the material call of IA cannot be passed normally with other parameters, etc. The IA in the text is ItemsAdder

**Comment by 157946a** [comment]
你先换个方法试试,前面是固定的,你可以不用把整节用参数,比如material: 'source:IA:参数'然后上面设置参数的地方就用你IA的物品名guis:slot_opaque

**Comment by 157946a** [comment]
你先换个方法试试,前面是固定的,你可以不用把整节用参数,比如material: 'source:IA:参数'然后上面设置参数的地方就用你IA的物品名guis:slot_opaque

**Comment by 157946a** [comment]
你先换个方法试试,前面是固定的,你可以不用把整节用参数,比如material: 'source:IA:参数'然后上面设置参数的地方就用你IA的物品名guis:slot_opaque

**Comment by Caishangqi** [comment]
> 你先换个方法试试,前面是固定的,你可以不用把整节用参数,比如material: 'source:IA:参数'然后上面设置参数的地方就用你IA的物品名guis:slot_opaque
不行额
还是接收不到material
https://paste.ubuntu.com/p/TMCpjWC3GW/

**Comment by 157946a** [comment]
方便把IA的一套发上来我测试吗

**Comment by Caishangqi** [comment]
> 方便把IA的一套发上来我测试吗

发邮箱吗，数据有点大

**Comment by Neige7** [comment]
尝试暂时使用子图标凑合凑合
```
  'B':
    display:
      material: 'stone'
    icons:
      - condition: 'money *2000'
        priority: 1
        display:
          material: source:IA:guis:button_locked
          name: '1'
      - display:
          material: source:IA:guis:button_locked
          name: '2'
```

**Comment by Caishangqi** [comment]
> 尝试暂时使用子图标凑合凑合
> 
> ```
>   'B':
>     display:
>       material: 'stone'
>     icons:
>       - condition: 'money *2000'
>         display:
>           material: source:IA:guis:button_locked
>           name: '1'
>       - display:
>           material: source:IA:guis:button_locked
>           name: '2'
> ```

好的，谢谢了

**Comment by Score2** [comment]
```
  B:
    display:
      material: 'source:IA:{ke: if money *2000 then set test to *guis:button_locked else set test to *guis:button_locked get test}'
      name: 'fvar i'
      amount: '1'
```
试试这样呢?

**Comment by 157946a** [comment]
关闭此帖吧,ke函数条件返回的内容有点迷,最好是用参数,临时数据这些来设置
