### ISSUE TITLE
[Bug]: TrMenu 3.01 子服安装 SkinsRestorer 时玩家头颅材质无法正常读取

### ISSUE THREAD

**Issue by Yurinann** [InsinuateProjects/TrMenu#76]
**Describe the bug**
Bungee 跨服，Bungee 与子服同时安装 SkinsRestorer，使用 TrMenu Wiki 中写法，玩家头颅材质无法正常获取（显示为默认 Steve）

**To Reproduce**
1. material: 'head:%player_name%' (或 material: 'source:HeadDatabase:myHead')
2. 打开菜单
3. 无法正常读取，#78 修复后后台无报错

**Expected behavior**
理论上应当正常读取。（子服未安装 SkinsRestorer 时可以正常读取）

**Server Information**
```
TrMenu Dump Information (Date: 2022-01-03 13:57:50)

| Server OS: Windows Server 2019 amd64 10.0
| Server software: git-Paper-407 (MC: 1.17.1) (1.17.1-R0.1-SNAPSHOT)
| Java version: 17.0.1

| TrMenu: 3.01
Installed Plugins: 
· AlonsoLevels - 2.2.3-BETA (0 KB)
· AlonsoTags - 2.0.7-BETA (0 KB)
· Citizens - 2.0.29-SNAPSHOT (build 2416) (0 KB)
· ConsoleSpamFix - 1.8.6 (0 KB)
· CurrentTime - 1.0.1 (0 KB)
· DecentHolograms - 2.2.5 (0 KB)
· DogHook - 1.1-SNAPSHOT (0 KB)
· FastAsyncWorldEdit - 2.0.0-SNAPSHOT-44;0994ea1 (0 KB)
· GadgetsMenu - 5.1.1 (0 KB)
· HanamuraCore - 1.2.0 (0 KB)
· HanamuraLobby - 1.1.1 (0 KB)
· HeadDatabase - 4.15.1 (0 KB)
· Images - 2.2.4 (0 KB)
· ItemJoin - 5.2.3-RELEASE-b789 (0 KB)
· LibsDisguises - 10.0.26 (0 KB)
· LuckPerms - 5.3.94 (0 KB)
· NBTAPI - 2.8.0 (0 KB)
· NoBlackSky - 2.5 (0 KB)
· PictureLogin - 1.6 (0 KB)
· PlaceholderAPI - 2.11.1 (0 KB)
· PlayerPoints - 3.1.0 (0 KB)
· PointLogger - 1.0.2 (0 KB)
· ProtocolLib - 4.7.1-SNAPSHOT-b536 (0 KB)
· RotatingHeads - 1.3.3 (0 KB)
· ScriptBlockPlus - 2.2.1 (0 KB)
· ServerUtils - 3.4.0 (0 KB)
· SkinsRestorer - 14.1.10 (0 KB)
· TAB - 3.0.2-pre2 (0 KB)
· TAB-Bridge - 1.6.0 (0 KB)
· TrChat - 1.90-R5 (0 KB)
· TrMenu - 3.01 (0 KB)
· UserPrefix - 2.2.1 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· ViaVersion - 4.1.1 (0 KB)
· WITP - 2.8c (0 KB)
· ZMusic-Addon - 1.4 (0 KB)
· momojs - 1.0.3 (0 KB)
· spark - 1.6.4 (0 KB)
```
https://paste.helpch.at/uwapudoneq.

**Comment by 157946a** [comment]
是bc端吗

**Comment by Yurinann** [comment]
> 是bc端吗,打开bc模式了?

使用了 Waterfall 进行跨服，但 TrMenu 并未与其有任何关联。

**Comment by Yurinann** [comment]
> 你先回答我的问题

bungeecord: true

**Comment by 157946a** [comment]
bc的话,bc的plugins有装skin吗

**Comment by Yurinann** [comment]
> > 是bc端吗,打开bc模式了?
> 
> 使用了 Waterfall 进行跨服，但 TrMenu 并未与其有任何关联。
> 
> 刚刚看到 #78 我也尝试一下

结果出来了，同样 bungeecord=false 在单端运行可以正常显示。

**Comment by Yurinann** [comment]
> bc的话,bc的plugins有装skin吗

如果指的是 SkinsRestorer 的话，有装，且为最新版；子服同样有

**Comment by Yurinann** [comment]
> > bc的话,bc的plugins有装skin吗
> 
> 如果指的是 SkinsRestorer 的话，有装，且为最新版；子服同样有

补充：移除了 SkinsRestorer 仍无显示

**Comment by 157946a** [comment]
那很简单,将bc模式打开,子服的skin删除即可

**Comment by Yurinann** [comment]
> 那很简单,将bc模式打开,子服的skin删除即可
> 注: 是所有子服,有一个子服有都将不会正常使用

已经移除，现在正常了，感谢帮助。
（如果方便的话，想要了解一下是什么原因

**Comment by Yurinann** [comment]
我查看到 https://github.com/InsinuateProjects/TrMenu/commit/3f922ba62aa29fd00852fc827ad6a4516f5e5c05 有关于 #78 相同问题的修复，故再次尝试，但仍旧无法显示。

**Comment by Yurinann** [comment]
该问题在 3.1.0 版本已经无法复现，看起来已经被修复。

**Comment by Score2** [comment]
> 该问题在 3.1.0 版本已经无法复现，看起来已经被修复。

我在近期的更新中并没有对该问题进行修复，也行是巧合
