### ISSUE TITLE
Bungeecord头颅材质无法加载

### ISSUE THREAD

**Issue by lanzhihry** [InsinuateProjects/TrMenu#78]
使用bungeecord,并在spigot.yml中打开bungeecord后头颅材质无法加载,关闭后则一切正常

**Comment by 157946a** [comment]
是否是和这位的一样,如果是等待他的结果然后尝试解决方法
https://github.com/InsinuateProjects/TrMenu/issues/76

**Comment by Yurinann** [comment]
#76 尝试我的解决方法，感谢 @157946a ！
