### ISSUE TITLE
TrMenu-3.0-PRE-26 头颅交互事件报错

### ISSUE THREAD

**Issue by Yurinann** [InsinuateProjects/TrMenu#79]
**Describe the bug**
进入游戏后，使用头颅交互后台出现报错：

当手持头颅对空气点击 左/右 键时，出现如下报错：
https://paste.dismail.de/?e18446974534a795#2Vs1Jt8xDP7dDETMK4mKa2WNScPkoZMZeUa6ykm5byxv

当手持头颅对方块/实体点击右键时，出现如下报错：
https://paste.dismail.de/?4e59136fa0d2b779#4RA5fyCucg9qtcmGSDTasGCfwcWjiJFGVma6Ja237oxF

当手持头颅对方块/实体点击左键时，出现如下报错：
https://paste.dismail.de/?7a6e5c80420fb839#FLYm1NDBi4EPPuZLCSHVaYB7rtU9u2zf8wCDZiNrbLLV

看起来没有影响到正常功能

**To Reproduce**
1. 加入游戏
2. 手持头颅与空气/实体/方块交互
3. 后台报错

**Expected behavior**
没有报错

**Screenshots**
参考描述部分

**Additional context**
经检查，TrMenu 除菜单内物品 Material 的玩家头颅调用 (head:%player_name%) 外无任何涉及头颅的操作。

**Server Information**
```
TrMenu Dump Information (Date: 2021-09-28 15:08:59)

| Server OS: Windows Server 2019 amd64 10.0
| Server software: git-Purpur-1171 (MC: 1.16.5) (1.16.5-R0.1-SNAPSHOT)
| Java version: 16.0.2

| TabooLib: 6.0.0-PRE
| TrMenu: 3.0-PRE-26
Installed Plugins: 
· AdvancedColorAPI - 0.1 (0 KB)
· Adyeshach - 1.3.21 (0 KB)
· AuthMe - 5.6.0-SNAPSHOT-b2463 (0 KB)
· DogHook - 1.1-SNAPSHOT (0 KB)
· GadgetsMenu - 4.5.3 (0 KB)
· GoldenCrates - 3.11.0 (0 KB)
· HeadDatabase - 4.14.1 (0 KB)
· HolographicDisplays - 2.4.9 (0 KB)
· HuacunLobby - 0.1.2-patch2 (0 KB)
· ItemJoin - 5.2.2-RELEASE-b734 (0 KB)
· LibsDisguises - 10.0.26 (0 KB)
· LuckPerms - 5.3.68 (0 KB)
· NexEngine - 2.0.7.4 (0 KB)
· PPRMB - 1.3.1-BETA (0 KB)
· PictureLogin - 1.6 (0 KB)
· PlaceholderAPI - 2.10.10 (0 KB)
· PlayerPoints - 3.0.3 (0 KB)
· PocketGames - 3.24.7 (0 KB)
· ProtocolLib - 4.7.0 (0 KB)
· ScriptBlockPlus - 2.1.6 (0 KB)
· ServersNPC - 3.6 (0 KB)
· TAB - 2.9.2 (0 KB)
· TrChat - 1.90-R2 (0 KB)
· TrHologram - 2.4-pre20 (0 KB)
· TrMenu - 3.0-PRE-26 (0 KB)
· UserPrefix - 2.1.0 (0 KB)
· VTitleAuth - 1.0 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· ViaVersion - 4.0.1 (0 KB)
· WITP - 2.6 (0 KB)
```

**Comment by Yurinann** [comment]
> **Describe the bug**
> 进入游戏后后台玩家交互事件报错，不确定问题起因（多次实验暂未找到明显规律）
> 看起来没有影响到正常功能
> 
> **To Reproduce**
> 
> 1. 加入游戏
> 2. 报错
> 
> **Expected behavior**
> 没有报错
> 
> **Screenshots**
> https://paste.dismail.de/?ef47ccf1b6df5b9b#dBb28AM6oSeW1viLZfcJAtYNzZSCveT55KKFiPSAk6r
> 报错链接
> 
> **Additional context**
> 无
> 
> **Server Information**
> 
> ```
> TrMenu Dump Information (Date: 2021-09-28 15:08:59)
> 
> | Server OS: Windows Server 2019 amd64 10.0
> | Server software: git-Purpur-1171 (MC: 1.16.5) (1.16.5-R0.1-SNAPSHOT)
> | Java version: 16.0.2
> 
> | TabooLib: 6.0.0-PRE
> | TrMenu: 3.0-PRE-26
> Installed Plugins: 
> · AdvancedColorAPI - 0.1 (0 KB)
> · Adyeshach - 1.3.21 (0 KB)
> · AuthMe - 5.6.0-SNAPSHOT-b2463 (0 KB)
> · Citizens - 2.0.28-SNAPSHOT (build 2372) (0 KB)
> · DogHook - 1.1-SNAPSHOT (0 KB)
> · GadgetsMenu - 4.5.3 (0 KB)
> · GoldenCrates - 3.11.0 (0 KB)
> · HeadDatabase - 4.14.1 (0 KB)
> · HolographicDisplays - 2.4.9 (0 KB)
> · HuacunLobby - 0.1.2-patch2 (0 KB)
> · ItemJoin - 5.2.2-RELEASE-b734 (0 KB)
> · LibsDisguises - 10.0.26 (0 KB)
> · LuckPerms - 5.3.68 (0 KB)
> · NexEngine - 2.0.7.4 (0 KB)
> · PPRMB - 1.3.1-BETA (0 KB)
> · PictureLogin - 1.6 (0 KB)
> · PlaceholderAPI - 2.10.10 (0 KB)
> · PlayerPoints - 3.0.3 (0 KB)
> · PocketGames - 3.24.7 (0 KB)
> · ProtocolLib - 4.7.0 (0 KB)
> · ScriptBlockPlus - 2.1.6 (0 KB)
> · ServersNPC - 3.6 (0 KB)
> · TAB - 2.9.2 (0 KB)
> · TrChat - 1.90-R2 (0 KB)
> · TrHologram - 2.4-pre20 (0 KB)
> · TrMenu - 3.0-PRE-26 (0 KB)
> · UserPrefix - 2.0.0 (0 KB)
> · VTitleAuth - 1.0 (0 KB)
> · Vault - 1.7.3-b131 (0 KB)
> · ViaVersion - 4.0.1 (0 KB)
> · WITP - 2.6 (0 KB)
> ```
> 
> https://paste.helpch.at/yotelebetu.



> **Describe the bug**
> 进入游戏后，使用头颅交互后台出现报错：
> 
> 当手持头颅对空气点击 左/右 键时，出现如下报错：
> https://paste.dismail.de/?e18446974534a795#2Vs1Jt8xDP7dDETMK4mKa2WNScPkoZMZeUa6ykm5byxv
> 
> 当手持头颅对方块/实体点击右键时，出现如下报错：
> https://paste.dismail.de/?4e59136fa0d2b779#4RA5fyCucg9qtcmGSDTasGCfwcWjiJFGVma6Ja237oxF
> 
> 当手持头颅对方块/实体点击左键时，出现如下报错：
> https://paste.dismail.de/?7a6e5c80420fb839#FLYm1NDBi4EPPuZLCSHVaYB7rtU9u2zf8wCDZiNrbLLV
> 
> 看起来没有影响到正常功能
> 
> **To Reproduce**
> 
> 1. 加入游戏
> 2. 手持头颅与空气/实体/方块交互
> 3. 后台报错
> 
> **Expected behavior**
> 没有报错
> 
> **Screenshots**
> 参考描述部分
> 
> **Additional context**
> 无
> 
> **Server Information**
> 
> ```
> TrMenu Dump Information (Date: 2021-09-28 15:08:59)
> 
> | Server OS: Windows Server 2019 amd64 10.0
> | Server software: git-Purpur-1171 (MC: 1.16.5) (1.16.5-R0.1-SNAPSHOT)
> | Java version: 16.0.2
> 
> | TabooLib: 6.0.0-PRE
> | TrMenu: 3.0-PRE-26
> Installed Plugins: 
> · AdvancedColorAPI - 0.1 (0 KB)
> · Adyeshach - 1.3.21 (0 KB)
> · AuthMe - 5.6.0-SNAPSHOT-b2463 (0 KB)
> · DogHook - 1.1-SNAPSHOT (0 KB)
> · GadgetsMenu - 4.5.3 (0 KB)
> · GoldenCrates - 3.11.0 (0 KB)
> · HeadDatabase - 4.14.1 (0 KB)
> · HolographicDisplays - 2.4.9 (0 KB)
> · HuacunLobby - 0.1.2-patch2 (0 KB)
> · ItemJoin - 5.2.2-RELEASE-b734 (0 KB)
> · LibsDisguises - 10.0.26 (0 KB)
> · LuckPerms - 5.3.68 (0 KB)
> · NexEngine - 2.0.7.4 (0 KB)
> · PPRMB - 1.3.1-BETA (0 KB)
> · PictureLogin - 1.6 (0 KB)
> · PlaceholderAPI - 2.10.10 (0 KB)
> · PlayerPoints - 3.0.3 (0 KB)
> · PocketGames - 3.24.7 (0 KB)
> · ProtocolLib - 4.7.0 (0 KB)
> · ScriptBlockPlus - 2.1.6 (0 KB)
> · ServersNPC - 3.6 (0 KB)
> · TAB - 2.9.2 (0 KB)
> · TrChat - 1.90-R2 (0 KB)
> · TrHologram - 2.4-pre20 (0 KB)
> · TrMenu - 3.0-PRE-26 (0 KB)
> · UserPrefix - 2.1.0 (0 KB)
> · VTitleAuth - 1.0 (0 KB)
> · Vault - 1.7.3-b131 (0 KB)
> · ViaVersion - 4.0.1 (0 KB)
> · WITP - 2.6 (0 KB)
> ```

重新补充了问题描述，在一定范围内得到了问题起因。

**Comment by Score2** [comment]
尝试使用最新的构建验证是否解决了该问题:)

**Comment by Yurinann** [comment]
> 尝试使用最新的构建验证是否解决了该问题:)

多次尝试操作均无报错。感谢修复
