### ISSUE TITLE
ViaVersion跨版本无法打开菜单

### ISSUE THREAD

**Issue by qaz197418i** [InsinuateProjects/TrMenu#8]
服务端:paper 1.12.2
客户端:1.16.5
ViaVersion跨版本支持后，使用1.14+的客户端进入服务器会无法打开任何6行的菜单
![image](https://user-images.githubusercontent.com/30312760/128623619-d30bf215-2dd3-4e29-bf9a-27c66e294572.png)

**Comment by Score2** [comment]
TabooLib/TabooLib#140
