### ISSUE TITLE
Cannot load properly in paper-1.17.1-257

### ISSUE THREAD

**Issue by Spectator-TiAmo** [InsinuateProjects/TrMenu#82]
**Describe the bug**
The console reports errors when the plugin is loaded, but the configuration file can be generated normally. And the plugin stops running after the console reports an error.

**To Reproduce**
1. Put the plugins into the plugins folder.
2. Start the server.

**Expected behavior**
I don't know what's wrong, I think it should works fine...

**Screenshots**

![~6F() 1O@OKA(F~07P@}VIP](https://user-images.githubusercontent.com/91328191/135607731-0eb1dafc-85f9-4240-9dd4-6d2dc5087a73.png)

**Additional context**
When executing '/trm debug dump' it prompts 'Unknown command. Type "/help" for help'. I don't know where I can find the TabooLib version,so in the **Server Information** I didn't fill in | TabooLib:
There is a run log posted here, if you need to provide any other reports please feel free to do so.
[https://paste.helpch.at/raw/zesufenoqu](url)
Thank you in advance :D

**Server Information**
> Use command `/trm debug dump` to get the information
> Copy the information to below
e.g.
```
TrMenu Dump Information (Date: 2021-10-01 18:31:04)

| Server OS: Host: Windows Server 2016 10.0 (amd64)
| Server software: paper-1.17.1-257
| Java version: OpenJDK 64-Bit Server VM Zulu17.28+13-CA (build 17+35-LTS, mixed mode, sharing)

| TabooLib: 
| TrMenu: 3.0-RC-1
Installed Plugins: 
· PlaceholderAPI - 2.10.10
· VoidGen - 2.0
· TrMenu - 3.0-RC-1

**Comment by Score2** [comment]
待RC-2推送

**Comment by Spectator-TiAmo** [comment]
成功载入 老哥效率真的顶啊233
