### ISSUE TITLE
打开菜单出现分析kether shell超时的错误

### ISSUE THREAD

**Issue by qaz197418i** [InsinuateProjects/TrMenu#9]
服务端：paper 1.12.2
TrMenu版本：3.0-pre13
如题，这是菜单中反复使用到的一句kether语法
![image](https://user-images.githubusercontent.com/30312760/128623790-8de5e33c-93a5-4dd1-b27d-652be6938dc7.png)
![image](https://user-images.githubusercontent.com/30312760/128623825-c5688998-9092-4860-b105-1a8d3027fe26.png)

**Comment by Score2** [comment]
Fixed
