### ISSUE TITLE
[Bug]: Trmenu Kills The Server

### ISSUE THREAD

**Issue by kacperleague9** [InsinuateProjects/TrMenu#95]
### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

```
TrMenu Dump Information (Date: xxxx-xx-xx xx:xx:xx)

  | Server OS: Ubuntu 18
  | Server software: Purpur 1414
  | Java version: 16-hotspot

  | TabooLib: 6.0.3-14
  | TrMenu: RC-2
Installed Plugins:
  · Fresh server
```

### 🔍 Detailed description

```
1. Install trmenu
2. Start the server
3. Server dies when loading libraries start
```

### 🗄 Server log

```
Nothing suspicious in logs, cpu usage just drops to ~~1%
```

### ⚙ Configurations

```
Default config
```

**Comment by Score2** [comment]
In the next version, I will try to add detailed debugging information to find out the reason for the download failure faster.

**Comment by 157946a** [comment]
Have you tried the latest version?

**Comment by kacperleague9** [comment]
its resolved
